const NUTRITION_DB_NAME = "elateFitNutritionDB";
const NUTRITION_DB_VERSION = 1;
const NUTRITION_STORE = "foodEntries";
const PROFILE_DB_NAME = "elateFitUserProfileDB";
const PROFILE_STORE_NAME = "profiles";
const PROFILE_RECORD_ID = "profile";

const foodCatalog = {
  // ==========================================
  // 1. GRAINS & MILLETS (Raw & Boiled)
  // ==========================================
  rice: {
    label: "Rice",
    calories: 130,
    protein: 2.7,
    saturatedFat: 0.1,
    unsaturatedFat: 0.2,
    solubleFiber: 0.1,
    insolubleFiber: 0.3,
    vitaminA: 0,
    vitaminC: 0,
    vitaminD: 0,
    vitaminE: 0,
    vitaminK: 0,
    vitaminB1: 0.02,
    vitaminB2: 0.01,
    vitaminB3: 0.4,
    vitaminB6: 0.05,
    folate: 0.003,
    vitaminB12: 0,
    calcium: 10,
    iron: 0.2,
    magnesium: 12,
    zinc: 0.4,
    iodine: 0,
    selenium: 0.007,
    copper: 0.05,
    potassium: 35,
    phosphorus: 43,
  },
  boiled_rice: {
    label: "Boiled Rice",
    calories: 123,
    protein: 2.5,
    saturatedFat: 0.1,
    unsaturatedFat: 0.2,
    solubleFiber: 0.1,
    insolubleFiber: 0.3,
    vitaminA: 0,
    vitaminC: 0,
    vitaminD: 0,
    vitaminE: 0,
    vitaminK: 0,
    vitaminB1: 0.01,
    vitaminB2: 0.01,
    vitaminB3: 0.3,
    vitaminB6: 0.04,
    folate: 0.002,
    vitaminB12: 0,
    calcium: 9,
    iron: 0.1,
    magnesium: 10,
    zinc: 0.3,
    iodine: 0,
    selenium: 0.005,
    copper: 0.04,
    potassium: 29,
    phosphorus: 37,
  },
  brown_rice: {
    label: "Brown Rice",
    calories: 111,
    protein: 2.6,
    saturatedFat: 0.2,
    unsaturatedFat: 0.6,
    solubleFiber: 0.4,
    insolubleFiber: 3.1,
    vitaminA: 0,
    vitaminC: 0,
    vitaminD: 0,
    vitaminE: 0.2,
    vitaminK: 0,
    vitaminB1: 0.1,
    vitaminB2: 0.02,
    vitaminB3: 1.5,
    vitaminB6: 0.1,
    folate: 0.004,
    vitaminB12: 0,
    calcium: 10,
    iron: 0.4,
    magnesium: 43,
    zinc: 0.6,
    iodine: 0,
    selenium: 0.01,
    copper: 0.1,
    potassium: 43,
    phosphorus: 83,
  },
  wheat: {
    label: "Wheat",
    calories: 340,
    protein: 13.7,
    saturatedFat: 0.4,
    unsaturatedFat: 0.8,
    solubleFiber: 1.2,
    insolubleFiber: 10.0,
    vitaminA: 0.003,
    vitaminC: 0,
    vitaminD: 0,
    vitaminE: 1.0,
    vitaminK: 0.002,
    vitaminB1: 0.4,
    vitaminB2: 0.1,
    vitaminB3: 5.5,
    vitaminB6: 0.3,
    folate: 0.038,
    vitaminB12: 0,
    calcium: 34,
    iron: 3.6,
    magnesium: 137,
    zinc: 2.6,
    iodine: 0.003,
    selenium: 0.07,
    copper: 0.4,
    potassium: 363,
    phosphorus: 346,
  },
  boiled_wheat: {
    label: "Boiled Wheat",
    calories: 125,
    protein: 4.8,
    saturatedFat: 0.1,
    unsaturatedFat: 0.3,
    solubleFiber: 0.5,
    insolubleFiber: 3.5,
    vitaminA: 0.001,
    vitaminC: 0,
    vitaminD: 0,
    vitaminE: 0.3,
    vitaminK: 0.001,
    vitaminB1: 0.1,
    vitaminB2: 0.03,
    vitaminB3: 1.8,
    vitaminB6: 0.1,
    folate: 0.012,
    vitaminB12: 0,
    calcium: 12,
    iron: 1.2,
    magnesium: 45,
    zinc: 0.8,
    iodine: 0.001,
    selenium: 0.02,
    copper: 0.1,
    potassium: 120,
    phosphorus: 115,
  },
  oats: {
    label: "Oats",
    calories: 389,
    protein: 16.9,
    saturatedFat: 1.2,
    unsaturatedFat: 3.5,
    solubleFiber: 4.0,
    insolubleFiber: 6.2,
    vitaminA: 0,
    vitaminC: 0,
    vitaminD: 0,
    vitaminE: 0.4,
    vitaminK: 0.002,
    vitaminB1: 0.8,
    vitaminB2: 0.1,
    vitaminB3: 1.0,
    vitaminB6: 0.1,
    folate: 0.056,
    vitaminB12: 0,
    calcium: 54,
    iron: 4.7,
    magnesium: 177,
    zinc: 4.0,
    iodine: 0.002,
    selenium: 0.028,
    copper: 0.6,
    potassium: 429,
    phosphorus: 523,
  },
  cooked_oats: {
    label: "Cooked Oats",
    calories: 71,
    protein: 2.5,
    saturatedFat: 0.2,
    unsaturatedFat: 0.8,
    solubleFiber: 1.0,
    insolubleFiber: 1.5,
    vitaminA: 0,
    vitaminC: 0,
    vitaminD: 0,
    vitaminE: 0.1,
    vitaminK: 0,
    vitaminB1: 0.15,
    vitaminB2: 0.02,
    vitaminB3: 0.2,
    vitaminB6: 0.02,
    folate: 0.01,
    vitaminB12: 0,
    calcium: 10,
    iron: 0.9,
    magnesium: 32,
    zinc: 0.7,
    iodine: 0,
    selenium: 0.005,
    copper: 0.1,
    potassium: 78,
    phosphorus: 95,
  },
  jowar: {
    label: "Jowar (Sorghum)",
    calories: 339,
    protein: 11.3,
    saturatedFat: 0.5,
    unsaturatedFat: 1.5,
    solubleFiber: 1.5,
    insolubleFiber: 8.0,
    vitaminA: 0,
    vitaminC: 0,
    vitaminD: 0,
    vitaminE: 0.5,
    vitaminK: 0,
    vitaminB1: 0.2,
    vitaminB2: 0.1,
    vitaminB3: 2.9,
    vitaminB6: 0.4,
    folate: 0.02,
    vitaminB12: 0,
    calcium: 28,
    iron: 4.4,
    magnesium: 165,
    zinc: 1.6,
    iodine: 0.002,
    selenium: 0.012,
    copper: 0.3,
    potassium: 350,
    phosphorus: 287,
  },
  boiled_jowar: {
    label: "Boiled Jowar",
    calories: 140,
    protein: 4.5,
    saturatedFat: 0.2,
    unsaturatedFat: 0.6,
    solubleFiber: 0.6,
    insolubleFiber: 3.2,
    vitaminA: 0,
    vitaminC: 0,
    vitaminD: 0,
    vitaminE: 0.2,
    vitaminK: 0,
    vitaminB1: 0.08,
    vitaminB2: 0.04,
    vitaminB3: 1.1,
    vitaminB6: 0.15,
    folate: 0.008,
    vitaminB12: 0,
    calcium: 11,
    iron: 1.7,
    magnesium: 65,
    zinc: 0.6,
    iodine: 0.001,
    selenium: 0.005,
    copper: 0.1,
    potassium: 135,
    phosphorus: 110,
  },
  bajra: {
    label: "Bajra (Pearl Millet)",
    calories: 361,
    protein: 11.6,
    saturatedFat: 0.5,
    unsaturatedFat: 3.5,
    solubleFiber: 1.2,
    insolubleFiber: 7.3,
    vitaminA: 0,
    vitaminC: 0,
    vitaminD: 0,
    vitaminE: 0.8,
    vitaminK: 0,
    vitaminB1: 0.3,
    vitaminB2: 0.2,
    vitaminB3: 2.3,
    vitaminB6: 0.3,
    folate: 0.035,
    vitaminB12: 0,
    calcium: 42,
    iron: 8.0,
    magnesium: 137,
    zinc: 3.1,
    iodine: 0,
    selenium: 0.015,
    copper: 0.5,
    potassium: 390,
    phosphorus: 296,
  },
  boiled_bajra: {
    label: "Boiled Bajra",
    calories: 135,
    protein: 4.2,
    saturatedFat: 0.2,
    unsaturatedFat: 1.2,
    solubleFiber: 0.5,
    insolubleFiber: 2.8,
    vitaminA: 0,
    vitaminC: 0,
    vitaminD: 0,
    vitaminE: 0.3,
    vitaminK: 0,
    vitaminB1: 0.1,
    vitaminB2: 0.07,
    vitaminB3: 0.8,
    vitaminB6: 0.1,
    folate: 0.012,
    vitaminB12: 0,
    calcium: 15,
    iron: 3.0,
    magnesium: 50,
    zinc: 1.1,
    iodine: 0,
    selenium: 0.005,
    copper: 0.2,
    potassium: 145,
    phosphorus: 110,
  },
  ragi: {
    label: "Ragi (Finger Millet)",
    calories: 328,
    protein: 7.3,
    saturatedFat: 0.3,
    unsaturatedFat: 1.5,
    solubleFiber: 1.8,
    insolubleFiber: 9.5,
    vitaminA: 0,
    vitaminC: 0,
    vitaminD: 0,
    vitaminE: 0.1,
    vitaminK: 0,
    vitaminB1: 0.4,
    vitaminB2: 0.2,
    vitaminB3: 1.1,
    vitaminB6: 0.1,
    folate: 0.015,
    vitaminB12: 0,
    calcium: 344,
    iron: 3.9,
    magnesium: 137,
    zinc: 2.3,
    iodine: 0,
    selenium: 0.01,
    copper: 0.4,
    potassium: 408,
    phosphorus: 283,
  },
  cooked_ragi: {
    label: "Cooked Ragi",
    calories: 115,
    protein: 2.6,
    saturatedFat: 0.1,
    unsaturatedFat: 0.5,
    solubleFiber: 0.6,
    insolubleFiber: 3.2,
    vitaminA: 0,
    vitaminC: 0,
    vitaminD: 0,
    vitaminE: 0,
    vitaminK: 0,
    vitaminB1: 0.14,
    vitaminB2: 0.07,
    vitaminB3: 0.4,
    vitaminB6: 0.03,
    folate: 0.005,
    vitaminB12: 0,
    calcium: 120,
    iron: 1.3,
    magnesium: 48,
    zinc: 0.8,
    iodine: 0,
    selenium: 0.003,
    copper: 0.1,
    potassium: 142,
    phosphorus: 99,
  },
  foxtail_millet: {
    label: "Foxtail Millet",
    calories: 331,
    protein: 12.3,
    saturatedFat: 0.4,
    unsaturatedFat: 2.0,
    solubleFiber: 1.5,
    insolubleFiber: 6.5,
    vitaminA: 0,
    vitaminC: 0,
    vitaminD: 0,
    vitaminE: 0.3,
    vitaminK: 0,
    vitaminB1: 0.6,
    vitaminB2: 0.1,
    vitaminB3: 3.2,
    vitaminB6: 0.3,
    folate: 0.015,
    vitaminB12: 0,
    calcium: 31,
    iron: 2.8,
    magnesium: 81,
    zinc: 2.4,
    iodine: 0,
    selenium: 0.012,
    copper: 0.3,
    potassium: 250,
    phosphorus: 290,
  },
  boiled_foxtail_millet: {
    label: "Boiled Foxtail Millet",
    calories: 120,
    protein: 4.0,
    saturatedFat: 0.1,
    unsaturatedFat: 0.7,
    solubleFiber: 0.5,
    insolubleFiber: 2.2,
    vitaminA: 0,
    vitaminC: 0,
    vitaminD: 0,
    vitaminE: 0.1,
    vitaminK: 0,
    vitaminB1: 0.2,
    vitaminB2: 0.03,
    vitaminB3: 1.1,
    vitaminB6: 0.1,
    folate: 0.005,
    vitaminB12: 0,
    calcium: 11,
    iron: 1.0,
    magnesium: 30,
    zinc: 0.8,
    iodine: 0,
    selenium: 0.004,
    copper: 0.1,
    potassium: 90,
    phosphorus: 105,
  },
  little_millet: {
    label: "Little Millet",
    calories: 341,
    protein: 7.7,
    saturatedFat: 0.6,
    unsaturatedFat: 2.2,
    solubleFiber: 1.4,
    insolubleFiber: 7.0,
    vitaminA: 0,
    vitaminC: 0,
    vitaminD: 0,
    vitaminE: 0.2,
    vitaminK: 0,
    vitaminB1: 0.3,
    vitaminB2: 0.1,
    vitaminB3: 3.2,
    vitaminB6: 0.2,
    folate: 0.01,
    vitaminB12: 0,
    calcium: 17,
    iron: 9.3,
    magnesium: 133,
    zinc: 3.7,
    iodine: 0,
    selenium: 0.01,
    copper: 0.2,
    potassium: 129,
    phosphorus: 220,
  },
  boiled_little_millet: {
    label: "Boiled Little Millet",
    calories: 125,
    protein: 2.8,
    saturatedFat: 0.2,
    unsaturatedFat: 0.8,
    solubleFiber: 0.5,
    insolubleFiber: 2.5,
    vitaminA: 0,
    vitaminC: 0,
    vitaminD: 0,
    vitaminE: 0.1,
    vitaminK: 0,
    vitaminB1: 0.1,
    vitaminB2: 0.03,
    vitaminB3: 1.1,
    vitaminB6: 0.07,
    folate: 0.003,
    vitaminB12: 0,
    calcium: 6,
    iron: 3.4,
    magnesium: 48,
    zinc: 1.3,
    iodine: 0,
    selenium: 0.003,
    copper: 0.1,
    potassium: 47,
    phosphorus: 80,
  },
  barnyard_millet: {
    label: "Barnyard Millet",
    calories: 307,
    protein: 6.2,
    saturatedFat: 0.2,
    unsaturatedFat: 1.1,
    solubleFiber: 1.2,
    insolubleFiber: 8.6,
    vitaminA: 0,
    vitaminC: 0,
    vitaminD: 0,
    vitaminE: 0.2,
    vitaminK: 0,
    vitaminB1: 0.3,
    vitaminB2: 0.1,
    vitaminB3: 4.2,
    vitaminB6: 0.2,
    folate: 0.015,
    vitaminB12: 0,
    calcium: 20,
    iron: 5.0,
    magnesium: 82,
    zinc: 3.0,
    iodine: 0,
    selenium: 0.01,
    copper: 0.2,
    potassium: 160,
    phosphorus: 280,
  },
  boiled_barnyard_millet: {
    label: "Boiled Barnyard Millet",
    calories: 110,
    protein: 2.2,
    saturatedFat: 0.1,
    unsaturatedFat: 0.4,
    solubleFiber: 0.4,
    insolubleFiber: 3.0,
    vitaminA: 0,
    vitaminC: 0,
    vitaminD: 0,
    vitaminE: 0.1,
    vitaminK: 0,
    vitaminB1: 0.1,
    vitaminB2: 0.03,
    vitaminB3: 1.5,
    vitaminB6: 0.07,
    folate: 0.005,
    vitaminB12: 0,
    calcium: 7,
    iron: 1.8,
    magnesium: 30,
    zinc: 1.1,
    iodine: 0,
    selenium: 0.003,
    copper: 0.1,
    potassium: 58,
    phosphorus: 100,
  },
  kodo_millet: {
    label: "Kodo Millet",
    calories: 309,
    protein: 8.3,
    saturatedFat: 0.4,
    unsaturatedFat: 1.6,
    solubleFiber: 1.6,
    insolubleFiber: 9.0,
    vitaminA: 0,
    vitaminC: 0,
    vitaminD: 0,
    vitaminE: 0.2,
    vitaminK: 0,
    vitaminB1: 0.15,
    vitaminB2: 0.09,
    vitaminB3: 2.0,
    vitaminB6: 0.2,
    folate: 0.02,
    vitaminB12: 0,
    calcium: 27,
    iron: 0.5,
    magnesium: 147,
    zinc: 0.7,
    iodine: 0,
    selenium: 0.01,
    copper: 0.2,
    potassium: 144,
    phosphorus: 188,
  },
  boiled_kodo_millet: {
    label: "Boiled Kodo Millet",
    calories: 115,
    protein: 3.0,
    saturatedFat: 0.1,
    unsaturatedFat: 0.6,
    solubleFiber: 0.6,
    insolubleFiber: 3.2,
    vitaminA: 0,
    vitaminC: 0,
    vitaminD: 0,
    vitaminE: 0.1,
    vitaminK: 0,
    vitaminB1: 0.05,
    vitaminB2: 0.03,
    vitaminB3: 0.7,
    vitaminB6: 0.07,
    folate: 0.007,
    vitaminB12: 0,
    calcium: 10,
    iron: 0.2,
    magnesium: 54,
    zinc: 0.2,
    iodine: 0,
    selenium: 0.003,
    copper: 0.1,
    potassium: 53,
    phosphorus: 69,
  },
  proso_millet: {
    label: "Proso Millet",
    calories: 341,
    protein: 11.0,
    saturatedFat: 0.5,
    unsaturatedFat: 2.5,
    solubleFiber: 1.3,
    insolubleFiber: 7.2,
    vitaminA: 0,
    vitaminC: 0,
    vitaminD: 0,
    vitaminE: 0.3,
    vitaminK: 0,
    vitaminB1: 0.4,
    vitaminB2: 0.1,
    vitaminB3: 4.5,
    vitaminB6: 0.3,
    folate: 0.01,
    vitaminB12: 0,
    calcium: 14,
    iron: 0.8,
    magnesium: 153,
    zinc: 1.4,
    iodine: 0,
    selenium: 0.012,
    copper: 0.3,
    potassium: 195,
    phosphorus: 206,
  },
  boiled_proso_millet: {
    label: "Boiled Proso Millet",
    calories: 128,
    protein: 3.8,
    saturatedFat: 0.2,
    unsaturatedFat: 0.9,
    solubleFiber: 0.5,
    insolubleFiber: 2.6,
    vitaminA: 0,
    vitaminC: 0,
    vitaminD: 0,
    vitaminE: 0.1,
    vitaminK: 0,
    vitaminB1: 0.15,
    vitaminB2: 0.04,
    vitaminB3: 1.6,
    vitaminB6: 0.1,
    folate: 0.003,
    vitaminB12: 0,
    calcium: 5,
    iron: 0.3,
    magnesium: 56,
    zinc: 0.5,
    iodine: 0,
    selenium: 0.004,
    copper: 0.1,
    potassium: 71,
    phosphorus: 75,
  },
  corn: {
    label: "Sweet Corn",
    calories: 86,
    protein: 3.3,
    saturatedFat: 0.2,
    unsaturatedFat: 1.0,
    solubleFiber: 0.8,
    insolubleFiber: 1.9,
    vitaminA: 0.009,
    vitaminC: 6.8,
    vitaminD: 0,
    vitaminE: 0.07,
    vitaminK: 0.0003,
    vitaminB1: 0.15,
    vitaminB2: 0.05,
    vitaminB3: 1.7,
    vitaminB6: 0.09,
    folate: 0.042,
    vitaminB12: 0,
    calcium: 2,
    iron: 0.5,
    magnesium: 37,
    zinc: 0.4,
    iodine: 0,
    selenium: 0.0006,
    copper: 0.05,
    potassium: 270,
    phosphorus: 89,
  },
  boiled_corn: {
    label: "Boiled Corn",
    calories: 96,
    protein: 3.4,
    saturatedFat: 0.3,
    unsaturatedFat: 1.2,
    solubleFiber: 0.9,
    insolubleFiber: 2.1,
    vitaminA: 0.013,
    vitaminC: 5.5,
    vitaminD: 0,
    vitaminE: 0.09,
    vitaminK: 0.0004,
    vitaminB1: 0.13,
    vitaminB2: 0.06,
    vitaminB3: 1.4,
    vitaminB6: 0.07,
    folate: 0.035,
    vitaminB12: 0,
    calcium: 3,
    iron: 0.4,
    magnesium: 26,
    zinc: 0.6,
    iodine: 0,
    selenium: 0.001,
    copper: 0.04,
    potassium: 218,
    phosphorus: 77,
  },
  sabudana: {
    label: "Sabudana (Tapioca Sago)",
    calories: 358,
    protein: 0.2,
    saturatedFat: 0.1,
    unsaturatedFat: 0.1,
    solubleFiber: 0.2,
    insolubleFiber: 0.3,
    vitaminA: 0,
    vitaminC: 0,
    vitaminD: 0,
    vitaminE: 0,
    vitaminK: 0,
    vitaminB1: 0,
    vitaminB2: 0,
    vitaminB3: 0,
    vitaminB6: 0,
    folate: 0.001,
    vitaminB12: 0,
    calcium: 20,
    iron: 1.2,
    magnesium: 1,
    zinc: 0.1,
    iodine: 0,
    selenium: 0.001,
    copper: 0.02,
    potassium: 11,
    phosphorus: 7,
  },
  boiled_sabudana: {
    label: "Boiled Sabudana",
    calories: 140,
    protein: 0.1,
    saturatedFat: 0.0,
    unsaturatedFat: 0.1,
    solubleFiber: 0.1,
    insolubleFiber: 0.1,
    vitaminA: 0,
    vitaminC: 0,
    vitaminD: 0,
    vitaminE: 0,
    vitaminK: 0,
    vitaminB1: 0,
    vitaminB2: 0,
    vitaminB3: 0,
    vitaminB6: 0,
    folate: 0,
    vitaminB12: 0,
    calcium: 8,
    iron: 0.4,
    magnesium: 0,
    zinc: 0,
    iodine: 0,
    selenium: 0,
    copper: 0.01,
    potassium: 4,
    phosphorus: 2,
  },
  quinoa: {
    label: "Quinoa",
    calories: 120,
    protein: 4.4,
    saturatedFat: 0.2,
    unsaturatedFat: 1.5,
    solubleFiber: 0.8,
    insolubleFiber: 2.0,
    vitaminA: 0.001,
    vitaminC: 0,
    vitaminD: 0,
    vitaminE: 0.6,
    vitaminK: 0,
    vitaminB1: 0.1,
    vitaminB2: 0.1,
    vitaminB3: 0.4,
    vitaminB6: 0.1,
    folate: 0.042,
    vitaminB12: 0,
    calcium: 17,
    iron: 1.5,
    magnesium: 64,
    zinc: 1.1,
    iodine: 0,
    selenium: 0.002,
    copper: 0.2,
    potassium: 172,
    phosphorus: 152,
  },

  // ==========================================
  // 2. PULSES & LEGUMES (Raw & Boiled)
  // ==========================================
  dal: {
    label: "Dal (Generic Moong/Toor)",
    calories: 116,
    protein: 9.0,
    saturatedFat: 0.1,
    unsaturatedFat: 0.2,
    solubleFiber: 1.3,
    insolubleFiber: 3.1,
    vitaminA: 0.001,
    vitaminC: 0,
    vitaminD: 0,
    vitaminE: 0.1,
    vitaminK: 0.002,
    vitaminB1: 0.1,
    vitaminB2: 0.05,
    vitaminB3: 0.6,
    vitaminB6: 0.1,
    folate: 0.1,
    vitaminB12: 0,
    calcium: 30,
    iron: 1.5,
    magnesium: 40,
    zinc: 1.0,
    iodine: 0,
    selenium: 0.002,
    copper: 0.1,
    potassium: 250,
    phosphorus: 100,
  },
  toor_dal: {
    label: "Toor Dal (Raw)",
    calories: 343,
    protein: 22.3,
    saturatedFat: 0.3,
    unsaturatedFat: 1.2,
    solubleFiber: 3.5,
    insolubleFiber: 11.5,
    vitaminA: 0.002,
    vitaminC: 0,
    vitaminD: 0,
    vitaminE: 0.2,
    vitaminK: 0.005,
    vitaminB1: 0.4,
    vitaminB2: 0.2,
    vitaminB3: 2.9,
    vitaminB6: 0.3,
    folate: 0.456,
    vitaminB12: 0,
    calcium: 130,
    iron: 5.2,
    magnesium: 183,
    zinc: 2.7,
    iodine: 0.002,
    selenium: 0.008,
    copper: 1.0,
    potassium: 1392,
    phosphorus: 367,
  },
  boiled_toor_dal: {
    label: "Boiled Toor Dal",
    calories: 115,
    protein: 7.5,
    saturatedFat: 0.1,
    unsaturatedFat: 0.4,
    solubleFiber: 1.2,
    insolubleFiber: 3.8,
    vitaminA: 0.001,
    vitaminC: 0,
    vitaminD: 0,
    vitaminE: 0.1,
    vitaminK: 0.002,
    vitaminB1: 0.1,
    vitaminB2: 0.05,
    vitaminB3: 0.8,
    vitaminB6: 0.1,
    folate: 0.13,
    vitaminB12: 0,
    calcium: 40,
    iron: 1.5,
    magnesium: 55,
    zinc: 0.8,
    iodine: 0.001,
    selenium: 0.002,
    copper: 0.3,
    potassium: 450,
    phosphorus: 115,
  },
  moong_dal: {
    label: "Moong Dal (Raw)",
    calories: 347,
    protein: 24.0,
    saturatedFat: 0.3,
    unsaturatedFat: 0.9,
    solubleFiber: 3.2,
    insolubleFiber: 13.0,
    vitaminA: 0.003,
    vitaminC: 4.8,
    vitaminD: 0,
    vitaminE: 0.5,
    vitaminK: 0.009,
    vitaminB1: 0.6,
    vitaminB2: 0.2,
    vitaminB3: 2.3,
    vitaminB6: 0.4,
    folate: 0.625,
    vitaminB12: 0,
    calcium: 132,
    iron: 6.7,
    magnesium: 189,
    zinc: 2.7,
    iodine: 0.002,
    selenium: 0.008,
    copper: 0.9,
    potassium: 1246,
    phosphorus: 367,
  },
  boiled_moong_dal: {
    label: "Boiled Moong Dal",
    calories: 105,
    protein: 7.0,
    saturatedFat: 0.1,
    unsaturatedFat: 0.3,
    solubleFiber: 1.0,
    insolubleFiber: 4.0,
    vitaminA: 0.001,
    vitaminC: 1.0,
    vitaminD: 0,
    vitaminE: 0.1,
    vitaminK: 0.003,
    vitaminB1: 0.15,
    vitaminB2: 0.06,
    vitaminB3: 0.6,
    vitaminB6: 0.1,
    folate: 0.159,
    vitaminB12: 0,
    calcium: 27,
    iron: 1.4,
    magnesium: 48,
    zinc: 0.8,
    iodine: 0.001,
    selenium: 0.002,
    copper: 0.3,
    potassium: 266,
    phosphorus: 99,
  },
  chana_dal: {
    label: "Chana Dal (Raw)",
    calories: 360,
    protein: 20.8,
    saturatedFat: 0.5,
    unsaturatedFat: 2.1,
    solubleFiber: 4.0,
    insolubleFiber: 11.0,
    vitaminA: 0.003,
    vitaminC: 1.5,
    vitaminD: 0,
    vitaminE: 0.8,
    vitaminK: 0.009,
    vitaminB1: 0.5,
    vitaminB2: 0.2,
    vitaminB3: 1.5,
    vitaminB6: 0.5,
    folate: 0.557,
    vitaminB12: 0,
    calcium: 105,
    iron: 6.2,
    magnesium: 115,
    zinc: 3.4,
    iodine: 0.003,
    selenium: 0.008,
    copper: 0.8,
    potassium: 875,
    phosphorus: 352,
  },
  boiled_chana_dal: {
    label: "Boiled Chana Dal",
    calories: 134,
    protein: 7.2,
    saturatedFat: 0.2,
    unsaturatedFat: 0.8,
    solubleFiber: 1.5,
    insolubleFiber: 4.2,
    vitaminA: 0.001,
    vitaminC: 0,
    vitaminD: 0,
    vitaminE: 0.2,
    vitaminK: 0.003,
    vitaminB1: 0.1,
    vitaminB2: 0.05,
    vitaminB3: 0.5,
    vitaminB6: 0.15,
    folate: 0.15,
    vitaminB12: 0,
    calcium: 35,
    iron: 2.0,
    magnesium: 40,
    zinc: 1.1,
    iodine: 0.001,
    selenium: 0.002,
    copper: 0.3,
    potassium: 280,
    phosphorus: 110,
  },
  masoor_dal: {
    label: "Masoor Dal (Raw)",
    calories: 353,
    protein: 25.0,
    saturatedFat: 0.4,
    unsaturatedFat: 1.0,
    solubleFiber: 3.0,
    insolubleFiber: 8.5,
    vitaminA: 0.002,
    vitaminC: 4.5,
    vitaminD: 0,
    vitaminE: 0.5,
    vitaminK: 0.005,
    vitaminB1: 0.9,
    vitaminB2: 0.2,
    vitaminB3: 2.6,
    vitaminB6: 0.5,
    folate: 0.479,
    vitaminB12: 0,
    calcium: 56,
    iron: 7.5,
    magnesium: 122,
    zinc: 3.3,
    iodine: 0.002,
    selenium: 0.008,
    copper: 0.5,
    potassium: 955,
    phosphorus: 281,
  },
  boiled_masoor_dal: {
    label: "Boiled Masoor Dal",
    calories: 116,
    protein: 9.0,
    saturatedFat: 0.1,
    unsaturatedFat: 0.4,
    solubleFiber: 1.1,
    insolubleFiber: 3.0,
    vitaminA: 0.001,
    vitaminC: 1.5,
    vitaminD: 0,
    vitaminE: 0.1,
    vitaminK: 0.002,
    vitaminB1: 0.2,
    vitaminB2: 0.06,
    vitaminB3: 1.0,
    vitaminB6: 0.2,
    folate: 0.181,
    vitaminB12: 0,
    calcium: 19,
    iron: 3.3,
    magnesium: 36,
    zinc: 1.3,
    iodine: 0.001,
    selenium: 0.003,
    copper: 0.2,
    potassium: 369,
    phosphorus: 180,
  },
  urad_dal: {
    label: "Urad Dal (Raw)",
    calories: 341,
    protein: 25.2,
    saturatedFat: 0.3,
    unsaturatedFat: 0.8,
    solubleFiber: 4.5,
    insolubleFiber: 13.5,
    vitaminA: 0.001,
    vitaminC: 0,
    vitaminD: 0,
    vitaminE: 0,
    vitaminK: 0,
    vitaminB1: 0.3,
    vitaminB2: 0.2,
    vitaminB3: 1.4,
    vitaminB6: 0.3,
    folate: 0.216,
    vitaminB12: 0,
    calcium: 138,
    iron: 7.6,
    magnesium: 267,
    zinc: 3.3,
    iodine: 0.002,
    selenium: 0.005,
    copper: 1.0,
    potassium: 983,
    phosphorus: 379,
  },
  boiled_urad_dal: {
    label: "Boiled Urad Dal",
    calories: 110,
    protein: 8.0,
    saturatedFat: 0.1,
    unsaturatedFat: 0.3,
    solubleFiber: 1.5,
    insolubleFiber: 4.5,
    vitaminA: 0,
    vitaminC: 0,
    vitaminD: 0,
    vitaminE: 0,
    vitaminK: 0,
    vitaminB1: 0.1,
    vitaminB2: 0.05,
    vitaminB3: 0.5,
    vitaminB6: 0.1,
    folate: 0.07,
    vitaminB12: 0,
    calcium: 45,
    iron: 2.2,
    magnesium: 80,
    zinc: 1.0,
    iodine: 0.001,
    selenium: 0.001,
    copper: 0.3,
    potassium: 300,
    phosphorus: 120,
  },
  rajma: {
    label: "Rajma (Kidney Beans - Raw)",
    calories: 333,
    protein: 23.6,
    saturatedFat: 0.5,
    unsaturatedFat: 1.2,
    solubleFiber: 6.0,
    insolubleFiber: 18.0,
    vitaminA: 0.001,
    vitaminC: 4.5,
    vitaminD: 0,
    vitaminE: 0.2,
    vitaminK: 0.008,
    vitaminB1: 0.5,
    vitaminB2: 0.2,
    vitaminB3: 2.1,
    vitaminB6: 0.4,
    folate: 0.394,
    vitaminB12: 0,
    calcium: 143,
    iron: 8.2,
    magnesium: 140,
    zinc: 2.8,
    iodine: 0.002,
    selenium: 0.003,
    copper: 0.8,
    potassium: 1406,
    phosphorus: 406,
  },
  boiled_rajma: {
    label: "Boiled Rajma",
    calories: 127,
    protein: 8.7,
    saturatedFat: 0.1,
    unsaturatedFat: 0.4,
    solubleFiber: 2.2,
    insolubleFiber: 6.5,
    vitaminA: 0,
    vitaminC: 1.2,
    vitaminD: 0,
    vitaminE: 0.03,
    vitaminK: 0.002,
    vitaminB1: 0.16,
    vitaminB2: 0.06,
    vitaminB3: 0.6,
    vitaminB6: 0.12,
    folate: 0.13,
    vitaminB12: 0,
    calcium: 28,
    iron: 2.9,
    magnesium: 45,
    zinc: 1.0,
    iodine: 0.001,
    selenium: 0.001,
    copper: 0.2,
    potassium: 403,
    phosphorus: 142,
  },
  chole: {
    label: "Kabuli Chana (Chickpeas - Raw)",
    calories: 364,
    protein: 19.0,
    saturatedFat: 0.6,
    unsaturatedFat: 3.5,
    solubleFiber: 5.0,
    insolubleFiber: 12.5,
    vitaminA: 0.003,
    vitaminC: 4.0,
    vitaminD: 0,
    vitaminE: 0.8,
    vitaminK: 0.009,
    vitaminB1: 0.5,
    vitaminB2: 0.2,
    vitaminB3: 1.5,
    vitaminB6: 0.5,
    folate: 0.557,
    vitaminB12: 0,
    calcium: 105,
    iron: 6.2,
    magnesium: 115,
    zinc: 3.4,
    iodine: 0.002,
    selenium: 0.008,
    copper: 0.8,
    potassium: 875,
    phosphorus: 366,
  },
  boiled_chole: {
    label: "Boiled Chole",
    calories: 164,
    protein: 8.9,
    saturatedFat: 0.3,
    unsaturatedFat: 1.6,
    solubleFiber: 2.0,
    insolubleFiber: 5.6,
    vitaminA: 0.001,
    vitaminC: 1.3,
    vitaminD: 0,
    vitaminE: 0.3,
    vitaminK: 0.004,
    vitaminB1: 0.1,
    vitaminB2: 0.06,
    vitaminB3: 0.5,
    vitaminB6: 0.1,
    folate: 0.172,
    vitaminB12: 0,
    calcium: 49,
    iron: 2.9,
    magnesium: 48,
    zinc: 1.5,
    iodine: 0.001,
    selenium: 0.003,
    copper: 0.3,
    potassium: 291,
    phosphorus: 168,
  },
  lobia: {
    label: "Black-Eyed Peas (Raw)",
    calories: 336,
    protein: 23.5,
    saturatedFat: 0.5,
    unsaturatedFat: 1.3,
    solubleFiber: 3.5,
    insolubleFiber: 15.0,
    vitaminA: 0.002,
    vitaminC: 1.5,
    vitaminD: 0,
    vitaminE: 0.4,
    vitaminK: 0.005,
    vitaminB1: 0.8,
    vitaminB2: 0.2,
    vitaminB3: 2.0,
    vitaminB6: 0.3,
    folate: 0.633,
    vitaminB12: 0,
    calcium: 110,
    iron: 8.2,
    magnesium: 333,
    zinc: 3.3,
    iodine: 0,
    selenium: 0.008,
    copper: 0.8,
    potassium: 1112,
    phosphorus: 424,
  },
  boiled_lobia: {
    label: "Boiled Lobia",
    calories: 116,
    protein: 7.7,
    saturatedFat: 0.2,
    unsaturatedFat: 0.4,
    solubleFiber: 1.2,
    insolubleFiber: 5.0,
    vitaminA: 0.001,
    vitaminC: 0,
    vitaminD: 0,
    vitaminE: 0.1,
    vitaminK: 0.002,
    vitaminB1: 0.2,
    vitaminB2: 0.05,
    vitaminB3: 0.4,
    vitaminB6: 0.1,
    folate: 0.208,
    vitaminB12: 0,
    calcium: 24,
    iron: 2.5,
    magnesium: 53,
    zinc: 1.3,
    iodine: 0,
    selenium: 0.003,
    copper: 0.2,
    potassium: 278,
    phosphorus: 156,
  },
  horse_gram: {
    label: "Horse Gram (Kulthi - Raw)",
    calories: 321,
    protein: 22.0,
    saturatedFat: 0.5,
    unsaturatedFat: 1.1,
    solubleFiber: 4.0,
    insolubleFiber: 15.5,
    vitaminA: 0.003,
    vitaminC: 1.0,
    vitaminD: 0,
    vitaminE: 0.1,
    vitaminK: 0,
    vitaminB1: 0.4,
    vitaminB2: 0.2,
    vitaminB3: 1.5,
    vitaminB6: 0.4,
    folate: 0.2,
    vitaminB12: 0,
    calcium: 287,
    iron: 7.6,
    magnesium: 150,
    zinc: 3.0,
    iodine: 0,
    selenium: 0.005,
    copper: 0.8,
    potassium: 800,
    phosphorus: 311,
  },
  boiled_horse_gram: {
    label: "Boiled Horse Gram",
    calories: 110,
    protein: 7.5,
    saturatedFat: 0.2,
    unsaturatedFat: 0.4,
    solubleFiber: 1.4,
    insolubleFiber: 5.2,
    vitaminA: 0.001,
    vitaminC: 0,
    vitaminD: 0,
    vitaminE: 0,
    vitaminK: 0,
    vitaminB1: 0.1,
    vitaminB2: 0.05,
    vitaminB3: 0.5,
    vitaminB6: 0.1,
    folate: 0.06,
    vitaminB12: 0,
    calcium: 90,
    iron: 2.5,
    magnesium: 45,
    zinc: 1.0,
    iodine: 0,
    selenium: 0.002,
    copper: 0.2,
    potassium: 250,
    phosphorus: 100,
  },
  moth_beans: {
    label: "Moth Beans (Matki - Raw)",
    calories: 343,
    protein: 23.0,
    saturatedFat: 0.5,
    unsaturatedFat: 1.2,
    solubleFiber: 3.8,
    insolubleFiber: 14.0,
    vitaminA: 0,
    vitaminC: 2.0,
    vitaminD: 0,
    vitaminE: 0.1,
    vitaminK: 0,
    vitaminB1: 0.5,
    vitaminB2: 0.1,
    vitaminB3: 1.8,
    vitaminB6: 0.3,
    folate: 0.3,
    vitaminB12: 0,
    calcium: 150,
    iron: 10.8,
    magnesium: 160,
    zinc: 2.5,
    iodine: 0,
    selenium: 0.005,
    copper: 0.7,
    potassium: 1100,
    phosphorus: 350,
  },
  boiled_moth_beans: {
    label: "Boiled Moth Beans",
    calories: 118,
    protein: 7.9,
    saturatedFat: 0.2,
    unsaturatedFat: 0.4,
    solubleFiber: 1.3,
    insolubleFiber: 4.8,
    vitaminA: 0,
    vitaminC: 0.5,
    vitaminD: 0,
    vitaminE: 0,
    vitaminK: 0,
    vitaminB1: 0.15,
    vitaminB2: 0.03,
    vitaminB3: 0.6,
    vitaminB6: 0.1,
    folate: 0.1,
    vitaminB12: 0,
    calcium: 45,
    iron: 3.5,
    magnesium: 50,
    zinc: 0.8,
    iodine: 0,
    selenium: 0.002,
    copper: 0.2,
    potassium: 350,
    phosphorus: 110,
  },
  green_gram: {
    label: "Green Gram Whole (Raw)",
    calories: 347,
    protein: 24.0,
    saturatedFat: 0.3,
    unsaturatedFat: 0.9,
    solubleFiber: 3.5,
    insolubleFiber: 13.0,
    vitaminA: 0.003,
    vitaminC: 4.8,
    vitaminD: 0,
    vitaminE: 0.5,
    vitaminK: 0.009,
    vitaminB1: 0.6,
    vitaminB2: 0.2,
    vitaminB3: 2.3,
    vitaminB6: 0.4,
    folate: 0.625,
    vitaminB12: 0,
    calcium: 132,
    iron: 6.7,
    magnesium: 189,
    zinc: 2.7,
    iodine: 0,
    selenium: 0.008,
    copper: 0.9,
    potassium: 1246,
    phosphorus: 367,
  },
  boiled_green_gram: {
    label: "Boiled Green Gram Whole",
    calories: 105,
    protein: 7.0,
    saturatedFat: 0.1,
    unsaturatedFat: 0.3,
    solubleFiber: 1.2,
    insolubleFiber: 4.5,
    vitaminA: 0.001,
    vitaminC: 1.0,
    vitaminD: 0,
    vitaminE: 0.1,
    vitaminK: 0.003,
    vitaminB1: 0.15,
    vitaminB2: 0.06,
    vitaminB3: 0.6,
    vitaminB6: 0.1,
    folate: 0.159,
    vitaminB12: 0,
    calcium: 27,
    iron: 1.4,
    magnesium: 48,
    zinc: 0.8,
    iodine: 0,
    selenium: 0.002,
    copper: 0.3,
    potassium: 266,
    phosphorus: 99,
  },
  matar: {
    label: "Dry Green Peas (Raw)",
    calories: 340,
    protein: 24.5,
    saturatedFat: 0.4,
    unsaturatedFat: 1.1,
    solubleFiber: 5.0,
    insolubleFiber: 20.0,
    vitaminA: 0.006,
    vitaminC: 1.8,
    vitaminD: 0,
    vitaminE: 0.1,
    vitaminK: 0.005,
    vitaminB1: 0.7,
    vitaminB2: 0.2,
    vitaminB3: 2.9,
    vitaminB6: 0.2,
    folate: 0.274,
    vitaminB12: 0,
    calcium: 55,
    iron: 4.4,
    magnesium: 115,
    zinc: 3.0,
    iodine: 0,
    selenium: 0.001,
    copper: 0.8,
    potassium: 981,
    phosphorus: 366,
  },
  boiled_matar: {
    label: "Boiled Green Peas",
    calories: 81,
    protein: 5.4,
    saturatedFat: 0.1,
    unsaturatedFat: 0.1,
    solubleFiber: 2.0,
    insolubleFiber: 3.0,
    vitaminA: 0.038,
    vitaminC: 14.2,
    vitaminD: 0,
    vitaminE: 0.1,
    vitaminK: 0.024,
    vitaminB1: 0.2,
    vitaminB2: 0.1,
    vitaminB3: 2.0,
    vitaminB6: 0.2,
    folate: 0.063,
    vitaminB12: 0,
    calcium: 27,
    iron: 1.5,
    magnesium: 39,
    zinc: 1.1,
    iodine: 0,
    selenium: 0.001,
    copper: 0.1,
    potassium: 271,
    phosphorus: 117,
  },
  soyabean: {
    label: "Soybean (Raw)",
    calories: 446,
    protein: 36.5,
    saturatedFat: 2.9,
    unsaturatedFat: 16.5,
    solubleFiber: 3.5,
    insolubleFiber: 6.0,
    vitaminA: 0.001,
    vitaminC: 6.0,
    vitaminD: 0,
    vitaminE: 0.8,
    vitaminK: 0.047,
    vitaminB1: 0.8,
    vitaminB2: 0.8,
    vitaminB3: 1.6,
    vitaminB6: 0.3,
    folate: 0.375,
    vitaminB12: 0,
    calcium: 277,
    iron: 15.7,
    magnesium: 280,
    zinc: 4.8,
    iodine: 0,
    selenium: 0.017,
    copper: 1.6,
    potassium: 1797,
    phosphorus: 704,
  },
  boiled_soyabean: {
    label: "Boiled Soybean",
    calories: 172,
    protein: 16.6,
    saturatedFat: 1.1,
    unsaturatedFat: 6.3,
    solubleFiber: 1.5,
    insolubleFiber: 2.5,
    vitaminA: 0,
    vitaminC: 1.7,
    vitaminD: 0,
    vitaminE: 0.3,
    vitaminK: 0.019,
    vitaminB1: 0.1,
    vitaminB2: 0.2,
    vitaminB3: 0.4,
    vitaminB6: 0.2,
    folate: 0.054,
    vitaminB12: 0,
    calcium: 102,
    iron: 5.1,
    magnesium: 86,
    zinc: 1.1,
    iodine: 0,
    selenium: 0.007,
    copper: 0.4,
    potassium: 515,
    phosphorus: 245,
  },

  // ==========================================
  // 3. VEGETABLES (Raw & Boiled)
  // ==========================================
  potato: {
    label: "Potato",
    calories: 77,
    protein: 2.0,
    saturatedFat: 0.0,
    unsaturatedFat: 0.1,
    solubleFiber: 0.3,
    insolubleFiber: 1.4,
    vitaminA: 0,
    vitaminC: 19.7,
    vitaminD: 0,
    vitaminE: 0.01,
    vitaminK: 0.001,
    vitaminB1: 0.08,
    vitaminB2: 0.03,
    vitaminB3: 1.0,
    vitaminB6: 0.2,
    folate: 0.016,
    vitaminB12: 0,
    calcium: 12,
    iron: 0.8,
    magnesium: 23,
    zinc: 0.2,
    iodine: 0,
    selenium: 0.0003,
    copper: 0.1,
    potassium: 421,
    phosphorus: 57,
  },
  boiled_potato: {
    label: "Boiled Potato",
    calories: 87,
    protein: 1.9,
    saturatedFat: 0.0,
    unsaturatedFat: 0.1,
    solubleFiber: 0.3,
    insolubleFiber: 1.5,
    vitaminA: 0,
    vitaminC: 13.0,
    vitaminD: 0,
    vitaminE: 0.01,
    vitaminK: 0.001,
    vitaminB1: 0.1,
    vitaminB2: 0.02,
    vitaminB3: 1.3,
    vitaminB6: 0.2,
    folate: 0.009,
    vitaminB12: 0,
    calcium: 5,
    iron: 0.3,
    magnesium: 20,
    zinc: 0.3,
    iodine: 0,
    selenium: 0.0002,
    copper: 0.1,
    potassium: 328,
    phosphorus: 44,
  },
  carrot: {
    label: "Carrot",
    calories: 41,
    protein: 0.9,
    saturatedFat: 0.0,
    unsaturatedFat: 0.1,
    solubleFiber: 0.9,
    insolubleFiber: 1.6,
    vitaminA: 0.835,
    vitaminC: 5.9,
    vitaminD: 0,
    vitaminE: 0.6,
    vitaminK: 0.013,
    vitaminB1: 0.06,
    vitaminB2: 0.05,
    vitaminB3: 0.9,
    vitaminB6: 0.1,
    folate: 0.019,
    vitaminB12: 0,
    calcium: 33,
    iron: 0.3,
    magnesium: 12,
    zinc: 0.2,
    iodine: 0,
    selenium: 0.0001,
    copper: 0.04,
    potassium: 320,
    phosphorus: 35,
  },
  boiled_carrot: {
    label: "Boiled Carrot",
    calories: 35,
    protein: 0.8,
    saturatedFat: 0.0,
    unsaturatedFat: 0.1,
    solubleFiber: 0.8,
    insolubleFiber: 1.5,
    vitaminA: 0.852,
    vitaminC: 3.6,
    vitaminD: 0,
    vitaminE: 1.1,
    vitaminK: 0.013,
    vitaminB1: 0.04,
    vitaminB2: 0.04,
    vitaminB3: 0.6,
    vitaminB6: 0.1,
    folate: 0.014,
    vitaminB12: 0,
    calcium: 30,
    iron: 0.3,
    magnesium: 10,
    zinc: 0.2,
    iodine: 0,
    selenium: 0.0006,
    copper: 0.02,
    potassium: 235,
    phosphorus: 30,
  },
  spinach: {
    label: "Spinach",
    calories: 23,
    protein: 2.9,
    saturatedFat: 0.1,
    unsaturatedFat: 0.1,
    solubleFiber: 0.6,
    insolubleFiber: 1.5,
    vitaminA: 0.469,
    vitaminC: 28.1,
    vitaminD: 0,
    vitaminE: 2.0,
    vitaminK: 0.482,
    vitaminB1: 0.07,
    vitaminB2: 0.1,
    vitaminB3: 0.7,
    vitaminB6: 0.1,
    folate: 0.194,
    vitaminB12: 0,
    calcium: 99,
    iron: 2.7,
    magnesium: 79,
    zinc: 0.5,
    iodine: 0,
    selenium: 0.001,
    copper: 0.1,
    potassium: 558,
    phosphorus: 49,
  },
  boiled_spinach: {
    label: "Boiled Spinach",
    calories: 23,
    protein: 3.0,
    saturatedFat: 0.1,
    unsaturatedFat: 0.1,
    solubleFiber: 0.7,
    insolubleFiber: 1.7,
    vitaminA: 0.524,
    vitaminC: 9.8,
    vitaminD: 0,
    vitaminE: 2.0,
    vitaminK: 0.493,
    vitaminB1: 0.09,
    vitaminB2: 0.2,
    vitaminB3: 0.4,
    vitaminB6: 0.2,
    folate: 0.146,
    vitaminB12: 0,
    calcium: 136,
    iron: 3.5,
    magnesium: 87,
    zinc: 0.7,
    iodine: 0,
    selenium: 0.001,
    copper: 0.1,
    potassium: 466,
    phosphorus: 56,
  },
  tomato: {
    label: "Tomato",
    calories: 18,
    protein: 0.9,
    saturatedFat: 0.0,
    unsaturatedFat: 0.1,
    solubleFiber: 0.2,
    insolubleFiber: 1.2,
    vitaminA: 0.042,
    vitaminC: 13.7,
    vitaminD: 0,
    vitaminE: 0.5,
    vitaminK: 0.007,
    vitaminB1: 0.03,
    vitaminB2: 0.01,
    vitaminB3: 0.5,
    vitaminB6: 0.08,
    folate: 0.015,
    vitaminB12: 0,
    calcium: 10,
    iron: 0.2,
    magnesium: 11,
    zinc: 0.1,
    iodine: 0,
    selenium: 0,
    copper: 0.05,
    potassium: 237,
    phosphorus: 24,
  },
  boiled_tomato: {
    label: "Boiled Tomato",
    calories: 24,
    protein: 1.1,
    saturatedFat: 0.0,
    unsaturatedFat: 0.1,
    solubleFiber: 0.3,
    insolubleFiber: 1.5,
    vitaminA: 0.042,
    vitaminC: 11.0,
    vitaminD: 0,
    vitaminE: 0.5,
    vitaminK: 0.007,
    vitaminB1: 0.03,
    vitaminB2: 0.02,
    vitaminB3: 0.6,
    vitaminB6: 0.08,
    folate: 0.01,
    vitaminB12: 0,
    calcium: 11,
    iron: 0.2,
    magnesium: 11,
    zinc: 0.1,
    iodine: 0,
    selenium: 0,
    copper: 0.06,
    potassium: 218,
    phosphorus: 26,
  },
  onion: {
    label: "Onion",
    calories: 40,
    protein: 1.1,
    saturatedFat: 0.0,
    unsaturatedFat: 0.0,
    solubleFiber: 0.5,
    insolubleFiber: 1.2,
    vitaminA: 0,
    vitaminC: 7.4,
    vitaminD: 0,
    vitaminE: 0.02,
    vitaminK: 0.0004,
    vitaminB1: 0.04,
    vitaminB2: 0.02,
    vitaminB3: 0.1,
    vitaminB6: 0.1,
    folate: 0.019,
    vitaminB12: 0,
    calcium: 23,
    iron: 0.2,
    magnesium: 10,
    zinc: 0.1,
    iodine: 0,
    selenium: 0.0005,
    copper: 0.03,
    potassium: 146,
    phosphorus: 29,
  },
  boiled_onion: {
    label: "Boiled Onion",
    calories: 39,
    protein: 1.0,
    saturatedFat: 0.0,
    unsaturatedFat: 0.0,
    solubleFiber: 0.5,
    insolubleFiber: 1.2,
    vitaminA: 0,
    vitaminC: 5.0,
    vitaminD: 0,
    vitaminE: 0.01,
    vitaminK: 0.0003,
    vitaminB1: 0.03,
    vitaminB2: 0.01,
    vitaminB3: 0.1,
    vitaminB6: 0.1,
    folate: 0.014,
    vitaminB12: 0,
    calcium: 22,
    iron: 0.2,
    magnesium: 10,
    zinc: 0.1,
    iodine: 0,
    selenium: 0.0004,
    copper: 0.03,
    potassium: 119,
    phosphorus: 28,
  },
  cauliflower: {
    label: "Cauliflower",
    calories: 25,
    protein: 1.9,
    saturatedFat: 0.0,
    unsaturatedFat: 0.1,
    solubleFiber: 0.8,
    insolubleFiber: 1.2,
    vitaminA: 0,
    vitaminC: 48.2,
    vitaminD: 0,
    vitaminE: 0.08,
    vitaminK: 0.015,
    vitaminB1: 0.05,
    vitaminB2: 0.06,
    vitaminB3: 0.5,
    vitaminB6: 0.1,
    folate: 0.057,
    vitaminB12: 0,
    calcium: 22,
    iron: 0.4,
    magnesium: 15,
    zinc: 0.2,
    iodine: 0,
    selenium: 0.0006,
    copper: 0.03,
    potassium: 299,
    phosphorus: 44,
  },
  boiled_cauliflower: {
    label: "Boiled Cauliflower",
    calories: 23,
    protein: 1.8,
    saturatedFat: 0.0,
    unsaturatedFat: 0.1,
    solubleFiber: 0.8,
    insolubleFiber: 1.3,
    vitaminA: 0,
    vitaminC: 44.3,
    vitaminD: 0,
    vitaminE: 0.07,
    vitaminK: 0.013,
    vitaminB1: 0.04,
    vitaminB2: 0.05,
    vitaminB3: 0.4,
    vitaminB6: 0.1,
    folate: 0.044,
    vitaminB12: 0,
    calcium: 16,
    iron: 0.3,
    magnesium: 9,
    zinc: 0.1,
    iodine: 0,
    selenium: 0.0004,
    copper: 0.02,
    potassium: 142,
    phosphorus: 32,
  },
  cabbage: {
    label: "Cabbage",
    calories: 25,
    protein: 1.3,
    saturatedFat: 0.0,
    unsaturatedFat: 0.1,
    solubleFiber: 0.6,
    insolubleFiber: 1.9,
    vitaminA: 0.005,
    vitaminC: 36.6,
    vitaminD: 0,
    vitaminE: 0.1,
    vitaminK: 0.076,
    vitaminB1: 0.06,
    vitaminB2: 0.04,
    vitaminB3: 0.2,
    vitaminB6: 0.1,
    folate: 0.043,
    vitaminB12: 0,
    calcium: 40,
    iron: 0.4,
    magnesium: 12,
    zinc: 0.1,
    iodine: 0,
    selenium: 0.0003,
    copper: 0.01,
    potassium: 170,
    phosphorus: 26,
  },
  boiled_cabbage: {
    label: "Boiled Cabbage",
    calories: 22,
    protein: 1.0,
    saturatedFat: 0.0,
    unsaturatedFat: 0.1,
    solubleFiber: 0.5,
    insolubleFiber: 1.7,
    vitaminA: 0.004,
    vitaminC: 30.0,
    vitaminD: 0,
    vitaminE: 0.1,
    vitaminK: 0.076,
    vitaminB1: 0.04,
    vitaminB2: 0.04,
    vitaminB3: 0.2,
    vitaminB6: 0.1,
    folate: 0.03,
    vitaminB12: 0,
    calcium: 35,
    iron: 0.2,
    magnesium: 12,
    zinc: 0.1,
    iodine: 0,
    selenium: 0.0002,
    copper: 0.01,
    potassium: 119,
    phosphorus: 18,
  },
  brinjal: {
    label: "Brinjal (Eggplant)",
    calories: 25,
    protein: 1.0,
    saturatedFat: 0.0,
    unsaturatedFat: 0.1,
    solubleFiber: 1.3,
    insolubleFiber: 1.7,
    vitaminA: 0.001,
    vitaminC: 2.2,
    vitaminD: 0,
    vitaminE: 0.3,
    vitaminK: 0.003,
    vitaminB1: 0.03,
    vitaminB2: 0.03,
    vitaminB3: 0.6,
    vitaminB6: 0.08,
    folate: 0.022,
    vitaminB12: 0,
    calcium: 9,
    iron: 0.2,
    magnesium: 14,
    zinc: 0.1,
    iodine: 0,
    selenium: 0.0003,
    copper: 0.08,
    potassium: 229,
    phosphorus: 24,
  },
  boiled_brinjal: {
    label: "Boiled Brinjal",
    calories: 35,
    protein: 0.8,
    saturatedFat: 0.0,
    unsaturatedFat: 0.1,
    solubleFiber: 1.5,
    insolubleFiber: 2.0,
    vitaminA: 0.001,
    vitaminC: 1.3,
    vitaminD: 0,
    vitaminE: 0.4,
    vitaminK: 0.002,
    vitaminB1: 0.07,
    vitaminB2: 0.01,
    vitaminB3: 0.6,
    vitaminB6: 0.08,
    folate: 0.014,
    vitaminB12: 0,
    calcium: 6,
    iron: 0.2,
    magnesium: 11,
    zinc: 0.1,
    iodine: 0,
    selenium: 0.0001,
    copper: 0.05,
    potassium: 123,
    phosphorus: 15,
  },
  bhindi: {
    label: "Bhindi (Okra / Ladyfinger)",
    calories: 33,
    protein: 1.9,
    saturatedFat: 0.0,
    unsaturatedFat: 0.1,
    solubleFiber: 1.8,
    insolubleFiber: 1.4,
    vitaminA: 0.036,
    vitaminC: 23.0,
    vitaminD: 0,
    vitaminE: 0.2,
    vitaminK: 0.031,
    vitaminB1: 0.2,
    vitaminB2: 0.06,
    vitaminB3: 1.0,
    vitaminB6: 0.2,
    folate: 0.06,
    vitaminB12: 0,
    calcium: 82,
    iron: 0.6,
    magnesium: 57,
    zinc: 0.5,
    iodine: 0,
    selenium: 0.0007,
    copper: 0.1,
    potassium: 299,
    phosphorus: 61,
  },
  boiled_bhindi: {
    label: "Boiled Bhindi",
    calories: 28,
    protein: 1.7,
    saturatedFat: 0.0,
    unsaturatedFat: 0.1,
    solubleFiber: 1.5,
    insolubleFiber: 1.2,
    vitaminA: 0.02,
    vitaminC: 16.3,
    vitaminD: 0,
    vitaminE: 0.2,
    vitaminK: 0.04,
    vitaminB1: 0.1,
    vitaminB2: 0.05,
    vitaminB3: 0.8,
    vitaminB6: 0.1,
    folate: 0.046,
    vitaminB12: 0,
    calcium: 77,
    iron: 0.4,
    magnesium: 36,
    zinc: 0.4,
    iodine: 0,
    selenium: 0.0004,
    copper: 0.09,
    potassium: 135,
    phosphorus: 32,
  },

  // ==========================================
  // 4. FRUITS (Raw)
  // ==========================================
  banana: {
    label: "Banana",
    calories: 89,
    protein: 1.1,
    saturatedFat: 0.1,
    unsaturatedFat: 0.1,
    solubleFiber: 0.7,
    insolubleFiber: 1.0,
    vitaminA: 0.003,
    vitaminC: 8.7,
    vitaminD: 0,
    vitaminE: 0.1,
    vitaminK: 0.0005,
    vitaminB1: 0.03,
    vitaminB2: 0.07,
    vitaminB3: 0.6,
    vitaminB6: 0.3,
    folate: 0.02,
    vitaminB12: 0,
    calcium: 5,
    iron: 0.2,
    magnesium: 27,
    zinc: 0.1,
    iodine: 0,
    selenium: 0.001,
    copper: 0.07,
    potassium: 358,
    phosphorus: 22,
  },
  apple: {
    label: "Apple",
    calories: 52,
    protein: 0.3,
    saturatedFat: 0.0,
    unsaturatedFat: 0.1,
    solubleFiber: 1.0,
    insolubleFiber: 1.2,
    vitaminA: 0.002,
    vitaminC: 4.6,
    vitaminD: 0,
    vitaminE: 0.1,
    vitaminK: 0.002,
    vitaminB1: 0.01,
    vitaminB2: 0.02,
    vitaminB3: 0.09,
    vitaminB6: 0.04,
    folate: 0.003,
    vitaminB12: 0,
    calcium: 6,
    iron: 0.1,
    magnesium: 5,
    zinc: 0.04,
    iodine: 0,
    selenium: 0,
    copper: 0.02,
    potassium: 107,
    phosphorus: 11,
  },
  mango: {
    label: "Mango",
    calories: 60,
    protein: 0.8,
    saturatedFat: 0.1,
    unsaturatedFat: 0.1,
    solubleFiber: 0.8,
    insolubleFiber: 1.0,
    vitaminA: 0.054,
    vitaminC: 36.4,
    vitaminD: 0,
    vitaminE: 0.9,
    vitaminK: 0.004,
    vitaminB1: 0.02,
    vitaminB2: 0.03,
    vitaminB3: 0.6,
    vitaminB6: 0.1,
    folate: 0.043,
    vitaminB12: 0,
    calcium: 11,
    iron: 0.1,
    magnesium: 10,
    zinc: 0.09,
    iodine: 0,
    selenium: 0.0006,
    copper: 0.1,
    potassium: 168,
    phosphorus: 14,
  },
  guava: {
    label: "Guava",
    calories: 68,
    protein: 2.55,
    saturatedFat: 0.1,
    unsaturatedFat: 0.4,
    solubleFiber: 2.0,
    insolubleFiber: 3.4,
    vitaminA: 0.031,
    vitaminC: 228.3,
    vitaminD: 0,
    vitaminE: 0.7,
    vitaminK: 0.002,
    vitaminB1: 0.06,
    vitaminB2: 0.04,
    vitaminB3: 1.0,
    vitaminB6: 0.1,
    folate: 0.049,
    vitaminB12: 0,
    calcium: 18,
    iron: 0.2,
    magnesium: 22,
    zinc: 0.2,
    iodine: 0,
    selenium: 0.0006,
    copper: 0.2,
    potassium: 417,
    phosphorus: 40,
  },
  pomegranate: {
    label: "Pomegranate",
    calories: 83,
    protein: 1.7,
    saturatedFat: 0.1,
    unsaturatedFat: 0.2,
    solubleFiber: 0.8,
    insolubleFiber: 3.0,
    vitaminA: 0,
    vitaminC: 10.2,
    vitaminD: 0,
    vitaminE: 0.6,
    vitaminK: 0.016,
    vitaminB1: 0.06,
    vitaminB2: 0.05,
    vitaminB3: 0.2,
    vitaminB6: 0.07,
    folate: 0.038,
    vitaminB12: 0,
    calcium: 10,
    iron: 0.3,
    magnesium: 12,
    zinc: 0.3,
    iodine: 0,
    selenium: 0.0005,
    copper: 0.1,
    potassium: 236,
    phosphorus: 36,
  },
  orange: {
    label: "Orange",
    calories: 47,
    protein: 0.9,
    saturatedFat: 0.0,
    unsaturatedFat: 0.0,
    solubleFiber: 0.8,
    insolubleFiber: 1.6,
    vitaminA: 0.011,
    vitaminC: 53.2,
    vitaminD: 0,
    vitaminE: 0.1,
    vitaminK: 0,
    vitaminB1: 0.08,
    vitaminB2: 0.04,
    vitaminB3: 0.2,
    vitaminB6: 0.06,
    folate: 0.03,
    vitaminB12: 0,
    calcium: 40,
    iron: 0.1,
    magnesium: 10,
    zinc: 0.07,
    iodine: 0,
    selenium: 0.0005,
    copper: 0.04,
    potassium: 181,
    phosphorus: 14,
  },
  coconut_water: {
    label: "Tender Coconut Water",
    calories: 19,
    protein: 0.7,
    saturatedFat: 0.0,
    unsaturatedFat: 0.0,
    solubleFiber: 0.0,
    insolubleFiber: 0.0,
    vitaminA: 0,
    vitaminC: 2.4,
    vitaminD: 0,
    vitaminE: 0,
    vitaminK: 0,
    vitaminB1: 0.03,
    vitaminB2: 0.05,
    vitaminB3: 0.08,
    vitaminB6: 0.03,
    folate: 0.003,
    vitaminB12: 0,
    calcium: 24,
    iron: 0.2,
    magnesium: 25,
    zinc: 0.1,
    iodine: 0,
    selenium: 0.001,
    copper: 0.04,
    potassium: 250,
    phosphorus: 20,
  },

  // ==========================================
  // 5. DAIRY PRODUCTS
  // ==========================================
  milk: {
    label: "Milk",
    calories: 61,
    protein: 3.2,
    saturatedFat: 1.9,
    unsaturatedFat: 0.8,
    solubleFiber: 0.0,
    insolubleFiber: 0.0,
    vitaminA: 0.046,
    vitaminC: 0,
    vitaminD: 0,
    vitaminE: 0.07,
    vitaminK: 0.0003,
    vitaminB1: 0.04,
    vitaminB2: 0.1,
    vitaminB3: 0.1,
    vitaminB6: 0.03,
    folate: 0.005,
    vitaminB12: 0.0004,
    calcium: 113,
    iron: 0.03,
    magnesium: 10,
    zinc: 0.4,
    iodine: 0.03,
    selenium: 0.003,
    copper: 0.02,
    potassium: 132,
    phosphorus: 84,
  },
  curd: {
    label: "Curd (Yogurt)",
    calories: 61,
    protein: 3.5,
    saturatedFat: 1.2,
    unsaturatedFat: 0.5,
    solubleFiber: 0.0,
    insolubleFiber: 0.0,
    vitaminA: 0.027,
    vitaminC: 0,
    vitaminD: 0,
    vitaminE: 0.03,
    vitaminK: 0.0002,
    vitaminB1: 0.04,
    vitaminB2: 0.2,
    vitaminB3: 0.1,
    vitaminB6: 0.03,
    folate: 0.011,
    vitaminB12: 0.0003,
    calcium: 121,
    iron: 0.05,
    magnesium: 12,
    zinc: 0.5,
    iodine: 0.03,
    selenium: 0.003,
    copper: 0.01,
    potassium: 155,
    phosphorus: 95,
  },
  paneer: {
    label: "Paneer",
    calories: 265,
    protein: 18.3,
    saturatedFat: 14.0,
    unsaturatedFat: 7.0,
    solubleFiber: 0.0,
    insolubleFiber: 0.0,
    vitaminA: 0.13,
    vitaminC: 0,
    vitaminD: 0,
    vitaminE: 0.3,
    vitaminK: 0.001,
    vitaminB1: 0.02,
    vitaminB2: 0.3,
    vitaminB3: 0.1,
    vitaminB6: 0.07,
    folate: 0.02,
    vitaminB12: 0.0015,
    calcium: 390,
    iron: 0.5,
    magnesium: 30,
    zinc: 1.5,
    iodine: 0.02,
    selenium: 0.01,
    copper: 0.05,
    potassium: 100,
    phosphorus: 280,
  },
  butter: {
    label: "Butter",
    calories: 717,
    protein: 0.85,
    saturatedFat: 51.0,
    unsaturatedFat: 21.0,
    solubleFiber: 0.0,
    insolubleFiber: 0.0,
    vitaminA: 0.684,
    vitaminC: 0,
    vitaminD: 0.001,
    vitaminE: 2.3,
    vitaminK: 0.007,
    vitaminB1: 0.005,
    vitaminB2: 0.03,
    vitaminB3: 0.04,
    vitaminB6: 0.003,
    folate: 0.003,
    vitaminB12: 0.0001,
    calcium: 24,
    iron: 0.02,
    magnesium: 2,
    zinc: 0.09,
    iodine: 0.01,
    selenium: 0.001,
    copper: 0,
    potassium: 24,
    phosphorus: 24,
  },

  // ==========================================
  // 6. NUTS & SEEDS (Raw & Roasted)
  // ==========================================
  peanuts: {
    label: "Peanuts (Raw)",
    calories: 567,
    protein: 25.8,
    saturatedFat: 7.3,
    unsaturatedFat: 36.0,
    solubleFiber: 2.1,
    insolubleFiber: 6.0,
    vitaminA: 0,
    vitaminC: 0,
    vitaminD: 0,
    vitaminE: 8.3,
    vitaminK: 0,
    vitaminB1: 0.6,
    vitaminB2: 0.1,
    vitaminB3: 12.0,
    vitaminB6: 0.3,
    folate: 0.24,
    vitaminB12: 0,
    calcium: 92,
    iron: 4.5,
    magnesium: 168,
    zinc: 3.2,
    iodine: 0,
    selenium: 0.007,
    copper: 1.1,
    potassium: 705,
    phosphorus: 376,
  },
  almonds: {
    label: "Almonds (Raw)",
    calories: 579,
    protein: 21.1,
    saturatedFat: 3.8,
    unsaturatedFat: 44.0,
    solubleFiber: 2.9,
    insolubleFiber: 9.5,
    vitaminA: 0,
    vitaminC: 0,
    vitaminD: 0,
    vitaminE: 25.6,
    vitaminK: 0,
    vitaminB1: 0.2,
    vitaminB2: 1.1,
    vitaminB3: 3.6,
    vitaminB6: 0.1,
    folate: 0.044,
    vitaminB12: 0,
    calcium: 268,
    iron: 3.7,
    magnesium: 270,
    zinc: 3.1,
    iodine: 0,
    selenium: 0.004,
    copper: 1.0,
    potassium: 733,
    phosphorus: 481,
  },
  cashews: {
    label: "Cashews (Raw)",
    calories: 553,
    protein: 18.2,
    saturatedFat: 7.8,
    unsaturatedFat: 32.7,
    solubleFiber: 1.0,
    insolubleFiber: 2.3,
    vitaminA: 0,
    vitaminC: 0.5,
    vitaminD: 0,
    vitaminE: 0.9,
    vitaminK: 0.034,
    vitaminB1: 0.4,
    vitaminB2: 0.05,
    vitaminB3: 1.0,
    vitaminB6: 0.4,
    folate: 0.025,
    vitaminB12: 0,
    calcium: 37,
    iron: 6.6,
    magnesium: 292,
    zinc: 5.7,
    iodine: 0,
    selenium: 0.019,
    copper: 2.1,
    potassium: 660,
    phosphorus: 593,
  },
  walnuts: {
    label: "Walnuts",
    calories: 654,
    protein: 15.2,
    saturatedFat: 6.1,
    unsaturatedFat: 58.0,
    solubleFiber: 1.9,
    insolubleFiber: 4.8,
    vitaminA: 0.001,
    vitaminC: 1.3,
    vitaminD: 0,
    vitaminE: 0.7,
    vitaminK: 0.002,
    vitaminB1: 0.3,
    vitaminB2: 0.1,
    vitaminB3: 1.1,
    vitaminB6: 0.5,
    folate: 0.098,
    vitaminB12: 0,
    calcium: 98,
    iron: 2.9,
    magnesium: 158,
    zinc: 3.0,
    iodine: 0,
    selenium: 0.004,
    copper: 1.5,
    potassium: 441,
    phosphorus: 346,
  },
  sunflower_seeds: {
    label: "Sunflower Seeds",
    calories: 584,
    protein: 20.8,
    saturatedFat: 4.5,
    unsaturatedFat: 43.0,
    solubleFiber: 3.0,
    insolubleFiber: 5.5,
    vitaminA: 0.002,
    vitaminC: 1.4,
    vitaminD: 0,
    vitaminE: 35.1,
    vitaminK: 0,
    vitaminB1: 1.4,
    vitaminB2: 0.3,
    vitaminB3: 8.3,
    vitaminB6: 1.3,
    folate: 0.227,
    vitaminB12: 0,
    calcium: 78,
    iron: 5.2,
    magnesium: 325,
    zinc: 5.0,
    iodine: 0,
    selenium: 0.053,
    copper: 1.8,
    potassium: 645,
    phosphorus: 660,
  },

  // ==========================================
  // 7. MEATS & EGGS (Boiled, Fried & Curried)
  // ==========================================
  egg: {
    label: "Egg (Whole Raw)",
    calories: 155,
    protein: 13.0,
    saturatedFat: 3.1,
    unsaturatedFat: 5.4,
    solubleFiber: 0.0,
    insolubleFiber: 0.0,
    vitaminA: 0.16,
    vitaminC: 0,
    vitaminD: 0.002,
    vitaminE: 1.0,
    vitaminK: 0.003,
    vitaminB1: 0.04,
    vitaminB2: 0.4,
    vitaminB3: 0.07,
    vitaminB6: 0.1,
    folate: 0.047,
    vitaminB12: 0.0011,
    calcium: 50,
    iron: 1.2,
    magnesium: 12,
    zinc: 1.2,
    iodine: 0.05,
    selenium: 0.03,
    copper: 0.07,
    potassium: 138,
    phosphorus: 198,
  },
  boiled_egg: {
    label: "Boiled Egg",
    calories: 155,
    protein: 12.6,
    saturatedFat: 3.3,
    unsaturatedFat: 5.3,
    solubleFiber: 0.0,
    insolubleFiber: 0.0,
    vitaminA: 0.14,
    vitaminC: 0,
    vitaminD: 0.002,
    vitaminE: 1.0,
    vitaminK: 0.003,
    vitaminB1: 0.04,
    vitaminB2: 0.5,
    vitaminB3: 0.06,
    vitaminB6: 0.1,
    folate: 0.044,
    vitaminB12: 0.001,
    calcium: 50,
    iron: 1.1,
    magnesium: 10,
    zinc: 1.0,
    iodine: 0.04,
    selenium: 0.03,
    copper: 0.07,
    potassium: 126,
    phosphorus: 172,
  },
  chicken: {
    label: "Chicken Breast (Raw)",
    calories: 165,
    protein: 31.0,
    saturatedFat: 1.0,
    unsaturatedFat: 1.6,
    solubleFiber: 0.0,
    insolubleFiber: 0.0,
    vitaminA: 0.006,
    vitaminC: 0,
    vitaminD: 0.0001,
    vitaminE: 0.2,
    vitaminK: 0,
    vitaminB1: 0.07,
    vitaminB2: 0.1,
    vitaminB3: 11.2,
    vitaminB6: 0.6,
    folate: 0.004,
    vitaminB12: 0.0003,
    calcium: 11,
    iron: 0.7,
    magnesium: 28,
    zinc: 0.8,
    iodine: 0.002,
    selenium: 0.02,
    copper: 0.03,
    potassium: 256,
    phosphorus: 212,
  },
  mutton: {
    label: "Mutton (Goat Meat - Raw)",
    calories: 143,
    protein: 27.1,
    saturatedFat: 1.8,
    unsaturatedFat: 1.5,
    solubleFiber: 0.0,
    insolubleFiber: 0.0,
    vitaminA: 0,
    vitaminC: 0,
    vitaminD: 0,
    vitaminE: 0.1,
    vitaminK: 0,
    vitaminB1: 0.1,
    vitaminB2: 0.2,
    vitaminB3: 4.8,
    vitaminB6: 0.3,
    folate: 0.005,
    vitaminB12: 0.0025,
    calcium: 17,
    iron: 3.7,
    magnesium: 22,
    zinc: 5.3,
    iodine: 0.003,
    selenium: 0.02,
    copper: 0.2,
    potassium: 405,
    phosphorus: 200,
  },
  fish_rohu: {
    label: "Rohu Fish (Raw)",
    calories: 97,
    protein: 17.5,
    saturatedFat: 0.5,
    unsaturatedFat: 1.2,
    solubleFiber: 0.0,
    insolubleFiber: 0.0,
    vitaminA: 0.015,
    vitaminC: 1.0,
    vitaminD: 0.005,
    vitaminE: 0.5,
    vitaminK: 0,
    vitaminB1: 0.05,
    vitaminB2: 0.06,
    vitaminB3: 2.0,
    vitaminB6: 0.2,
    folate: 0.01,
    vitaminB12: 0.002,
    calcium: 40,
    iron: 1.0,
    magnesium: 30,
    zinc: 1.0,
    iodine: 0.05,
    selenium: 0.03,
    copper: 0.1,
    potassium: 300,
    phosphorus: 200,
  },

  // ==========================================
  // 10. SOUTH INDIAN DISHES & SNACKS
  // ==========================================
  idli: {
    label: "Idli",
    calories: 58,
    protein: 2.0,
    saturatedFat: 0.1,
    unsaturatedFat: 0.3,
    solubleFiber: 0.3,
    insolubleFiber: 1.0,
    vitaminA: 0,
    vitaminC: 0,
    vitaminD: 0,
    vitaminE: 0,
    vitaminK: 0,
    vitaminB1: 0.03,
    vitaminB2: 0.01,
    vitaminB3: 0.3,
    vitaminB6: 0.02,
    folate: 0.008,
    vitaminB12: 0,
    calcium: 14,
    iron: 0.5,
    magnesium: 10,
    zinc: 0.2,
    iodine: 0,
    selenium: 0.001,
    copper: 0.03,
    potassium: 36,
    phosphorus: 30,
  },
  dosa: {
    label: "Plain Dosa",
    calories: 133,
    protein: 3.5,
    saturatedFat: 1.5,
    unsaturatedFat: 4.0,
    solubleFiber: 0.4,
    insolubleFiber: 1.2,
    vitaminA: 0.002,
    vitaminC: 0,
    vitaminD: 0,
    vitaminE: 0.2,
    vitaminK: 0.001,
    vitaminB1: 0.04,
    vitaminB2: 0.02,
    vitaminB3: 0.5,
    vitaminB6: 0.03,
    folate: 0.012,
    vitaminB12: 0,
    calcium: 15,
    iron: 0.8,
    magnesium: 15,
    zinc: 0.3,
    iodine: 0,
    selenium: 0.002,
    copper: 0.05,
    potassium: 65,
    phosphorus: 50,
  },

  // ==========================================
  // 11. NORTH INDIAN BREADS, CURRIES & DISHES
  // ==========================================
  roti: {
    label: "Chapati / Roti (Plain Wheat)",
    calories: 297,
    protein: 11.0,
    saturatedFat: 0.4,
    unsaturatedFat: 0.8,
    solubleFiber: 1.2,
    insolubleFiber: 6.0,
    vitaminA: 0,
    vitaminC: 0,
    vitaminD: 0,
    vitaminE: 0.3,
    vitaminK: 0,
    vitaminB1: 0.2,
    vitaminB2: 0.05,
    vitaminB3: 2.1,
    vitaminB6: 0.1,
    folate: 0.02,
    vitaminB12: 0,
    calcium: 20,
    iron: 2.5,
    magnesium: 70,
    zinc: 1.5,
    iodine: 0.001,
    selenium: 0.03,
    copper: 0.2,
    potassium: 180,
    phosphorus: 180,
  },
  dal_makhani: {
    label: "Dal Makhani",
    calories: 152,
    protein: 6.0,
    saturatedFat: 5.2,
    unsaturatedFat: 4.5,
    solubleFiber: 1.8,
    insolubleFiber: 5.0,
    vitaminA: 0.03,
    vitaminC: 2.0,
    vitaminD: 0,
    vitaminE: 0.5,
    vitaminK: 0.005,
    vitaminB1: 0.1,
    vitaminB2: 0.08,
    vitaminB3: 0.5,
    vitaminB6: 0.1,
    folate: 0.05,
    vitaminB12: 0.0001,
    calcium: 50,
    iron: 1.8,
    magnesium: 40,
    zinc: 0.8,
    iodine: 0.002,
    selenium: 0.002,
    copper: 0.2,
    potassium: 250,
    phosphorus: 120,
  },
};

let nutritionDb;
let selectedPeriod = 7;
let allEntries = [];
let userProfile = null;

function openNutritionDatabase() {
  return new Promise((resolve, reject) => {
    const request = indexedDB.open(NUTRITION_DB_NAME, NUTRITION_DB_VERSION);
    request.onupgradeneeded = (event) => {
      const db = event.target.result;
      if (!db.objectStoreNames.contains(NUTRITION_STORE)) {
        const store = db.createObjectStore(NUTRITION_STORE, { keyPath: "id" });
        store.createIndex("createdAt", "createdAt");
      }
    };
    request.onsuccess = () => resolve(request.result);
    request.onerror = () => reject(request.error);
  });
}

function getAllEntries() {
  return new Promise((resolve, reject) => {
    const request = nutritionDb
      .transaction(NUTRITION_STORE, "readonly")
      .objectStore(NUTRITION_STORE)
      .getAll();
    request.onsuccess = () => resolve(request.result || []);
    request.onerror = () => reject(request.error);
  });
}

function saveEntry(entry) {
  return new Promise((resolve, reject) => {
    const request = nutritionDb
      .transaction(NUTRITION_STORE, "readwrite")
      .objectStore(NUTRITION_STORE)
      .put(entry);
    request.onsuccess = () => resolve();
    request.onerror = () => reject(request.error);
  });
}

function deleteEntry(id) {
  return new Promise((resolve, reject) => {
    const request = nutritionDb
      .transaction(NUTRITION_STORE, "readwrite")
      .objectStore(NUTRITION_STORE)
      .delete(id);
    request.onsuccess = () => resolve();
    request.onerror = () => reject(request.error);
  });
}

function deleteAllEntries() {
  return new Promise((resolve, reject) => {
    const request = nutritionDb
      .transaction(NUTRITION_STORE, "readwrite")
      .objectStore(NUTRITION_STORE)
      .clear();
    request.onsuccess = () => resolve();
    request.onerror = () => reject(request.error);
  });
}

function openProfileDatabase() {
  return new Promise((resolve, reject) => {
    const request = indexedDB.open(PROFILE_DB_NAME, 1);
    request.onupgradeneeded = (event) => {
      const db = event.target.result;
      if (!db.objectStoreNames.contains(PROFILE_STORE_NAME)) {
        db.createObjectStore(PROFILE_STORE_NAME, { keyPath: "id" });
      }
    };
    request.onsuccess = () => resolve(request.result);
    request.onerror = () => reject(request.error);
  });
}

function getSavedProfile(db) {
  return new Promise((resolve, reject) => {
    const request = db
      .transaction(PROFILE_STORE_NAME, "readonly")
      .objectStore(PROFILE_STORE_NAME)
      .get(PROFILE_RECORD_ID);
    request.onsuccess = () => resolve(request.result || null);
    request.onerror = () => reject(request.error);
  });
}

function normalizeFoodName(value) {
  return value.trim().toLowerCase();
}

function getFood(value) {
  const key = normalizeFoodName(value);
  return (
    foodCatalog[key] ||
    Object.values(foodCatalog).find((food) => food.label.toLowerCase() === key)
  );
}

function renderFoodSuggestions(query) {
  const suggestions = document.getElementById("foodSuggestions");
  const normalizedQuery = normalizeFoodName(query);
  const matches = Object.values(foodCatalog).filter(
    (food) =>
      !normalizedQuery || food.label.toLowerCase().includes(normalizedQuery),
  );

  suggestions.innerHTML = matches
    .map(
      (food) =>
        `<button type="button" class="foodSuggestion" data-food="${food.label}" role="option">${food.label}<small>${food.calories} kcal - ${food.protein} g protein - ${food.saturatedFat} g saturated fat per 100 g</small></button>`,
    )
    .join("");
  suggestions.classList.toggle(
    "is-visible",
    matches.length > 0 &&
      document.activeElement === document.getElementById("foodSearch"),
  );
}

function formatDate(date) {
  return new Intl.DateTimeFormat(undefined, {
    month: "short",
    day: "numeric",
    year: "numeric",
  }).format(date);
}

function formatTime(date) {
  return new Intl.DateTimeFormat(undefined, {
    hour: "numeric",
    minute: "2-digit",
  }).format(date);
}

function dayKey(date) {
  const local = new Date(date);
  return `${local.getFullYear()}-${String(local.getMonth() + 1).padStart(2, "0")}-${String(local.getDate()).padStart(2, "0")}`;
}

function activityFactor(level) {
  const factors = {
    Sedentary: 1.2,
    Light: 1.375,
    Moderate: 1.55,
    Active: 1.725,
    "Very active": 1.9,
  };
  return factors[level] || 1.2;
}

function bodyTypeFactor(bodyType) {
  const factors = {
    Ectomorphic: 1.1,
    Mesomorphic: 1.0,
    Endomorphic: 0.9,
  };
  return factors[bodyType] || 1.0;
}

function targetFactor(target) {
  const factors = {
    "Lose weight": 0.85,
    "Maintain weight": 1.0,
    "Gain weight": 1.15,
  };
  return factors[target] || 1.0;
}

function proteinFactor(profile) {
  const factors = {
    Ectomorphic: 1.9,
    Mesomorphic: 1.7,
    Endomorphic: 1.5,
  };
  const base = factors[profile.bodyType] || 1.6;
  if (profile.target === "Gain weight") return base + 0.2;
  if (profile.target === "Lose weight") return Math.max(1.4, base - 0.1);
  return base;
}

function calculateNutritionTargets(profile) {
  const baseCalories =
    10 * profile.weight + 6.25 * profile.height - 5 * profile.age + 5;
  const calories = Math.round(
    baseCalories *
      activityFactor(profile.activityLevel) *
      bodyTypeFactor(profile.bodyType) *
      targetFactor(profile.target),
  );
  const protein = Math.round(profile.weight * proteinFactor(profile));
  return { calories, protein };
}

function calculateNutrition(food, grams) {
  return {
    calories: (food.calories * grams) / 100,
    protein: (food.protein * grams) / 100,
    saturatedFat: (food.saturatedFat * grams) / 100,
    unsaturatedFat: (food.unsaturatedFat * grams) / 100,
    solubleFiber: (food.solubleFiber * grams) / 100,
    insolubleFiber: (food.insolubleFiber * grams) / 100,
  };
}

const MICRONUTRIENTS = [
  [
    "vitaminA",
    "Vitamin A",
    0.6,
    "mg RAE",
    "Sweet potatoes, carrots, tuna, butternut squash, spinach, cantaloupe, lettuce, red bell peppers, chicken liver, mango",
  ],
  [
    "vitaminC",
    "Vitamin C",
    45,
    "mg",
    "Oranges, strawberries, kiwi, bell peppers, broccoli, Brussels sprouts, tomatoes, papaya, lemons, grapefruits",
  ],
  [
    "vitaminD",
    "Vitamin D",
    0.005,
    "mg",
    "Salmon, sardines, herring, canned tuna, cod liver oil, egg yolks, mushrooms, fortified milk, fortified orange juice, fortified cereals",
  ],
  [
    "vitaminE",
    "Vitamin E",
    10,
    "mg",
    "Sunflower seeds, almonds, peanuts, spinach, broccoli, hazelnuts, pine nuts, avocado, red bell peppers, mango",
  ],
  [
    "vitaminK",
    "Vitamin K",
    0.055,
    "mg",
    "Kale, spinach, broccoli, Brussels sprouts, cabbage, Swiss chard, collard greens, green beans, prunes, kiwi",
  ],
  [
    "vitaminB1",
    "Vitamin B1 (Thiamine)",
    1.1,
    "mg",
    "Sunflower seeds, brown rice, whole wheat, green peas, lentils, pecans, black beans, macadamia nuts, edamame",
  ],
  [
    "vitaminB2",
    "Vitamin B2 (Riboflavin)",
    1.1,
    "mg",
    "Milk, yogurt, cheese, eggs, chicken breast, salmon, almonds, spinach",
  ],
  [
    "vitaminB3",
    "Vitamin B3 (Niacin)",
    14,
    "mg NE",
    "Chicken breast, turkey breast, chicken liver, tuna, salmon, peanuts, avocado, brown rice, whole wheat, mushrooms",
  ],
  [
    "vitaminB6",
    "Vitamin B6",
    1.3,
    "mg",
    "Chickpeas, chicken liver, tuna, salmon, chicken breast, fortified cereals, potatoes, turkey, bananas, marinara sauce",
  ],
  [
    "folate",
    "Folate (Vitamin B9)",
    0.4,
    "mg DFE",
    "Spinach, black-eyed peas, asparagus, Brussels sprouts, romaine lettuce, avocado, broccoli, mustard greens, green peas, kidney beans",
  ],
  [
    "vitaminB12",
    "Vitamin B12",
    0.0024,
    "mg",
    "Chicken liver, clams, sardines, fortified nutritional yeast, trout, salmon, milk, yogurt, eggs",
  ],
  [
    "calcium",
    "Calcium",
    1000,
    "mg",
    "Milk, cheese, yogurt, fortified orange juice, winter squash, edamame, tofu, canned sardines, almonds, kale",
  ],
  [
    "iron",
    "Iron",
    8,
    "mg",
    "Red meat, poultry, seafood, beans, spinach, raisins, fortified cereals, peas, lentils",
  ],
  [
    "magnesium",
    "Magnesium",
    310,
    "mg",
    "Pumpkin seeds, chia seeds, almonds, spinach, cashews, peanuts, edamame, black beans, peanut butter, brown rice",
  ],
  [
    "zinc",
    "Zinc",
    8,
    "mg",
    "Oysters, crab, pumpkin seeds, turkey, cheddar cheese, shrimp, lentils, chickpeas",
  ],
  [
    "iodine",
    "Iodine",
    0.15,
    "mg",
    "Seaweed, cod, milk, yogurt, cheese, iodized salt, shrimp, tuna, eggs, prunes",
  ],
  [
    "selenium",
    "Selenium",
    0.055,
    "mg",
    "Brazil nuts, halibut, tuna, brown rice, eggs, turkey, chicken, cottage cheese, baked beans",
  ],
  [
    "copper",
    "Copper",
    0.9,
    "mg",
    "Oysters, shiitake mushrooms, tofu, sweet potatoes, sesame seeds, cashews, chickpeas, salmon, dark chocolate, turkey",
  ],
  [
    "potassium",
    "Potassium",
    3500,
    "mg",
    "Bananas, sweet potatoes, spinach, avocados, potatoes, white beans, tomatoes, yogurt, salmon, mushrooms",
  ],
  [
    "phosphorus",
    "Phosphorus",
    700,
    "mg",
    "Chicken, turkey, salmon, milk, yogurt, sunflower seeds, pumpkin seeds, almonds, whole grains",
  ],
];

function calculateMicronutrients(food, grams) {
  return Object.fromEntries(
    MICRONUTRIENTS.map(([key]) => [key, ((food[key] || 0) * grams) / 100]),
  );
}

function formatMicronutrientAmount(amount) {
  return amount.toFixed(5);
}

function renderMicronutrients(entries) {
  const container = document.getElementById("micronutrientList");
  if (!container) return;
  const totals = Object.fromEntries(MICRONUTRIENTS.map(([key]) => [key, 0]));

  entries.forEach((entry) => {
    const food = getFood(entry.foodKey || entry.foodLabel);
    if (!food) return;
    const values = calculateMicronutrients(food, entry.grams);
    MICRONUTRIENTS.forEach(([key]) => {
      totals[key] += values[key];
    });
  });

  container.innerHTML = MICRONUTRIENTS.map(
    ([key, label, reference, unit, foodSuggestions]) => {
      const consumed = totals[key];
      const percentage = Math.min(100, (consumed / reference) * 100);
      const guidance =
        consumed < reference
          ? `<div class="micronutrientGuidance"><strong>FOODS TO CONSIDER</strong><ul>${foodSuggestions
              .split(", ")
              .map((food) => `<li>${food}</li>`)
              .join("")}</ul></div>`
          : "";
      return `
      <div class="micronutrientCard">
        <div class="micronutrientHeader">
          <span>${label}</span>
          <strong>${formatMicronutrientAmount(consumed)} / ${reference} ${unit}</strong>
        </div>
        <div class="micronutrientProgressTrack" role="progressbar" aria-label="${label} daily intake" aria-valuemin="0" aria-valuemax="100" aria-valuenow="${percentage.toFixed(1)}">
          <span style="width: ${percentage.toFixed(1)}%"></span>
        </div>
        ${guidance}
      </div>`;
    },
  ).join("");
}

function setStatus(message, isError = true) {
  const status = document.getElementById("statusMessage");
  status.textContent = message;
  status.style.color = isError ? "#B42318" : "#757575";
}

function getTodayEntries() {
  const today = dayKey(new Date());
  return allEntries.filter((entry) => dayKey(entry.createdAt) === today);
}

function renderEntries() {
  const entries = getTodayEntries().sort(
    (a, b) => new Date(b.createdAt) - new Date(a.createdAt),
  );
  const list = document.getElementById("entryList");
  list.innerHTML = entries.length
    ? entries
        .map(
          (entry) => `
        <div class="entryRow">
            <div class="entryFood"><strong>${entry.foodLabel}</strong><small>${formatDate(new Date(entry.createdAt))} · ${formatTime(new Date(entry.createdAt))}</small></div>
            <span>${entry.grams} g</span><span>${entry.calories.toFixed(0)} kcal</span><span>${entry.protein.toFixed(1)} g</span>
            <span>${(entry.saturatedFat || 0).toFixed(1)} g</span><span>${(entry.unsaturatedFat || 0).toFixed(1)} g</span>
            <span>${(entry.solubleFiber || 0).toFixed(1)} g</span><span>${(entry.insolubleFiber || 0).toFixed(1)} g</span>
            <button type="button" class="deleteEntry" data-id="${entry.id}" data-food="${entry.foodLabel}" aria-label="Delete ${entry.foodLabel}"><i class="fa-solid fa-xmark"></i></button>
        </div>`,
        )
        .join("")
    : '<div class="entryEmpty">No food entries saved for today.</div>';
  const calories = entries.reduce((sum, entry) => sum + entry.calories, 0);
  const protein = entries.reduce((sum, entry) => sum + entry.protein, 0);
  const saturatedFat = entries.reduce(
    (sum, entry) => sum + (entry.saturatedFat || 0),
    0,
  );
  const unsaturatedFat = entries.reduce(
    (sum, entry) => sum + (entry.unsaturatedFat || 0),
    0,
  );
  const solubleFiber = entries.reduce(
    (sum, entry) => sum + (entry.solubleFiber || 0),
    0,
  );
  const insolubleFiber = entries.reduce(
    (sum, entry) => sum + (entry.insolubleFiber || 0),
    0,
  );
  document.getElementById("todayCalories").textContent =
    `${calories.toFixed(0)} kcal`;
  document.getElementById("todayProtein").textContent =
    `${protein.toFixed(1)} g`;
  document.getElementById("todayEntries").textContent = entries.length;
  document.getElementById("todaySaturatedFat").textContent =
    `${saturatedFat.toFixed(1)} g`;
  document.getElementById("todayUnsaturatedFat").textContent =
    `${unsaturatedFat.toFixed(1)} g`;
  document.getElementById("todaySolubleFiber").textContent =
    `${solubleFiber.toFixed(1)} g`;
  document.getElementById("todayInsolubleFiber").textContent =
    `${insolubleFiber.toFixed(1)} g`;
  renderMicronutrients(entries);
}

function renderProfileTargets() {
  const calorieCard = document.getElementById("calorieTargetCard");
  const proteinCard = document.getElementById("proteinTargetCard");
  const calorieValue = document.getElementById("calorieTargetValue");
  const calorieLeft = document.getElementById("calorieTargetLeft");
  const calorieBadge = document.getElementById("calorieTargetBadge");
  const proteinValue = document.getElementById("proteinTargetValue");
  const proteinLeft = document.getElementById("proteinTargetLeft");
  const proteinBadge = document.getElementById("proteinTargetBadge");
  if (!calorieCard || !proteinCard) return;

  const entries = getTodayEntries();
  const todayCalories = entries.reduce((sum, entry) => sum + entry.calories, 0);
  const todayProtein = entries.reduce((sum, entry) => sum + entry.protein, 0);

  if (!userProfile) {
    calorieCard.classList.remove("is-complete");
    proteinCard.classList.remove("is-complete");
    calorieValue.textContent = "Set profile";
    calorieLeft.textContent = "Add a profile to calculate your calorie target.";
    calorieBadge.innerHTML = "Profile needed";
    proteinValue.textContent = "Set profile";
    proteinLeft.textContent = "Add a profile to calculate your protein target.";
    proteinBadge.innerHTML = "Profile needed";
    return;
  }

  const targets = calculateNutritionTargets(userProfile);
  const calorieRemaining = targets.calories - todayCalories;
  const proteinRemaining = targets.protein - todayProtein;
  const calorieComplete = calorieRemaining <= 0;
  const proteinComplete = proteinRemaining <= 0;

  calorieCard.classList.toggle("is-complete", calorieComplete);
  proteinCard.classList.toggle("is-complete", proteinComplete);
  calorieValue.textContent = `${targets.calories} kcal`;
  calorieLeft.textContent = calorieComplete
    ? `Target reached. ${Math.abs(calorieRemaining).toFixed(0)} kcal over.`
    : `${calorieRemaining.toFixed(0)} kcal left to reach your target.`;
  calorieBadge.innerHTML = calorieComplete
    ? '<i class="fa-solid fa-star"></i> Target reached'
    : "In progress";
  proteinValue.textContent = `${targets.protein} g`;
  proteinLeft.textContent = proteinComplete
    ? `Target reached. ${Math.abs(proteinRemaining).toFixed(1)} g over.`
    : `${proteinRemaining.toFixed(1)} g left to reach your target.`;
  proteinBadge.innerHTML = proteinComplete
    ? '<i class="fa-solid fa-star"></i> Target reached'
    : "In progress";
}

function aggregateByDay(days) {
  const end = new Date();
  const values = [];
  for (let offset = days - 1; offset >= 0; offset -= 1) {
    const date = new Date(end);
    date.setDate(end.getDate() - offset);
    const key = dayKey(date);
    const dayEntries = allEntries.filter(
      (entry) => dayKey(entry.createdAt) === key,
    );
    values.push({
      key,
      label: new Intl.DateTimeFormat(undefined, {
        month: "short",
        day: "numeric",
      }).format(date),
      calories: dayEntries.reduce((sum, entry) => sum + entry.calories, 0),
      protein: dayEntries.reduce((sum, entry) => sum + entry.protein, 0),
    });
  }
  return values;
}

function drawChart(data) {
  const canvas = document.getElementById("nutritionChart");
  const context = canvas.getContext("2d");
  const width = canvas.clientWidth || 600;
  const height = canvas.clientHeight || 290;
  const ratio = window.devicePixelRatio || 1;
  canvas.width = width * ratio;
  canvas.height = height * ratio;
  context.setTransform(ratio, 0, 0, ratio, 0, 0);
  context.clearRect(0, 0, width, height);
  const padding = { top: 20, right: 16, bottom: 38, left: 44 };
  const chartWidth = width - padding.left - padding.right;
  const chartHeight = height - padding.top - padding.bottom;
  const maxValue = Math.max(
    10,
    ...data.map((day) => Math.max(day.calories, day.protein * 10)),
  );
  context.font = "11px Segoe UI, sans-serif";
  context.strokeStyle = "#DCE9DF";
  context.fillStyle = "#64756A";
  for (let tick = 0; tick <= 4; tick += 1) {
    const y = padding.top + chartHeight - (chartHeight * tick) / 4;
    context.beginPath();
    context.moveTo(padding.left, y);
    context.lineTo(width - padding.right, y);
    context.stroke();
    context.fillText(Math.round((maxValue * tick) / 4), 5, y + 4);
  }
  function drawLine(valueSelector, color, scale = 1) {
    context.beginPath();
    data.forEach((day, index) => {
      const x =
        padding.left + (chartWidth * index) / Math.max(1, data.length - 1);
      const y =
        padding.top +
        chartHeight -
        (chartHeight * day[valueSelector] * scale) / maxValue;
      index ? context.lineTo(x, y) : context.moveTo(x, y);
    });
    context.strokeStyle = color;
    context.lineWidth = 2.5;
    context.stroke();
    data.forEach((day, index) => {
      const x =
        padding.left + (chartWidth * index) / Math.max(1, data.length - 1);
      const y =
        padding.top +
        chartHeight -
        (chartHeight * day[valueSelector] * scale) / maxValue;
      context.fillStyle = "#ffffff";
      context.beginPath();
      context.arc(x, y, 4.5, 0, Math.PI * 2);
      context.fill();
      context.fillStyle = color;
      context.beginPath();
      context.arc(x, y, 3, 0, Math.PI * 2);
      context.fill();
    });
  }
  drawLine("calories", "#757575");
  drawLine("protein", "#15803D", 10);
  context.fillStyle = "#64756A";
  data.forEach((day, index) => {
    if (
      data.length <= 10 ||
      index % Math.ceil(data.length / 7) === 0 ||
      index === data.length - 1
    ) {
      const x =
        padding.left + (chartWidth * index) / Math.max(1, data.length - 1);
      context.fillText(day.label, x - 15, height - 12);
    }
  });
  context.fillStyle = "#757575";
  context.fillRect(width - 154, 10, 12, 3);
  context.fillStyle = "#24352A";
  context.fillText("Calories", width - 136, 14);
  context.fillStyle = "#15803D";
  context.fillRect(width - 76, 10, 12, 3);
  context.fillStyle = "#24352A";
  context.fillText("Protein", width - 58, 14);
}

function trendText(data, key, unit) {
  const split = Math.floor(data.length / 2);
  const previous = data.slice(0, split).reduce((sum, day) => sum + day[key], 0);
  const current = data.slice(split).reduce((sum, day) => sum + day[key], 0);
  if (!previous && !current) return "No data recorded in this period.";
  if (!previous) return "New intake recorded in the latest period.";
  const change = ((current - previous) / previous) * 100;
  return `${change >= 0 ? "up" : "down"} ${Math.abs(change).toFixed(0)}% versus the earlier period (${current.toFixed(0)} ${unit}).`;
}

function renderProgress() {
  const data = aggregateByDay(selectedPeriod);
  drawChart(data);
  document.getElementById("calorieTrend").textContent = trendText(
    data,
    "calories",
    "kcal",
  );
  document.getElementById("proteinTrend").textContent = trendText(
    data,
    "protein",
    "g",
  );
}

async function refreshDashboard() {
  allEntries = await getAllEntries();
  renderEntries();
  renderProfileTargets();
  renderProgress();
}

document.addEventListener("DOMContentLoaded", async function () {
  try {
    nutritionDb = await openNutritionDatabase();
    try {
      const profileDb = await openProfileDatabase();
      userProfile = await getSavedProfile(profileDb);
    } catch (error) {
      userProfile = null;
    }
    const dataList = document.getElementById("foodOptions");
    dataList.innerHTML = Object.values(foodCatalog)
      .map((food) => `<option value="${food.label}"></option>`)
      .join("");
    const foodSearch = document.getElementById("foodSearch");
    const foodSuggestions = document.getElementById("foodSuggestions");
    foodSearch.addEventListener("focus", function () {
      renderFoodSuggestions(this.value);
    });
    foodSearch.addEventListener("input", function () {
      renderFoodSuggestions(this.value);
      const food = getFood(this.value);
      document.getElementById("foodPreview").textContent = food
        ? `${food.label}: ${food.calories} kcal and ${food.protein} g protein per 100 g.`
        : "Choose a food to see its nutrition per 100 g.";
    });
    foodSearch.addEventListener("blur", function () {
      setTimeout(() => foodSuggestions.classList.remove("is-visible"), 150);
    });
    foodSuggestions.addEventListener("click", function (event) {
      const suggestion = event.target.closest(".foodSuggestion");
      if (!suggestion) return;
      foodSearch.value = suggestion.dataset.food;
      foodSearch.dispatchEvent(new Event("input", { bubbles: true }));
      foodSearch.focus();
    });
    document
      .getElementById("foodForm")
      .addEventListener("submit", async function (event) {
        event.preventDefault();
        const food = getFood(document.getElementById("foodSearch").value);
        const grams = Number(document.getElementById("enterGrams").value);
        if (!food || !grams || grams <= 0) {
          setStatus(
            "Choose a listed food and enter a gram amount greater than zero.",
          );
          return;
        }
        const nutrition = calculateNutrition(food, grams);
        await saveEntry({
          id: crypto.randomUUID
            ? crypto.randomUUID()
            : `${Date.now()}-${Math.random()}`,
          foodKey: normalizeFoodName(food.label),
          foodLabel: food.label,
          grams,
          calories: nutrition.calories,
          protein: nutrition.protein,
          saturatedFat: nutrition.saturatedFat,
          unsaturatedFat: nutrition.unsaturatedFat,
          solubleFiber: nutrition.solubleFiber,
          insolubleFiber: nutrition.insolubleFiber,
          createdAt: new Date().toISOString(),
        });
        this.reset();
        document.getElementById("foodPreview").textContent =
          "Food saved with the current date and time.";
        setStatus("Food added to today's journal.", false);
        await refreshDashboard();
      });
    document
      .getElementById("entryList")
      .addEventListener("click", async function (event) {
        const button = event.target.closest(".deleteEntry");
        if (!button) return;
        if (!confirm(`Delete ${button.dataset.food} from today's intake?`))
          return;
        await deleteEntry(button.dataset.id);
        await refreshDashboard();
      });
    document
      .getElementById("deleteAllButton")
      .addEventListener("click", async function () {
        if (!allEntries.length || !confirm("DELETE ALL SAVED FOOD ENTRIES?"))
          return;
        if (
          !confirm(
            "This will permanently delete every saved food entry. Continue?",
          )
        )
          return;
        await deleteAllEntries();
        setStatus("All saved food entries were deleted.", false);
        await refreshDashboard();
      });
    document.querySelectorAll(".periodButton").forEach((button) =>
      button.addEventListener("click", function () {
        selectedPeriod = Number(this.dataset.period);
        document
          .querySelectorAll(".periodButton")
          .forEach((item) => item.classList.remove("active"));
        this.classList.add("active");
        renderProgress();
      }),
    );
    window.addEventListener("resize", renderProgress);
    await refreshDashboard();
  } catch (error) {
    console.error("Unable to initialize nutrition journal:", error);
    setStatus("Nutrition storage is unavailable in this browser.");
  }
});
